### ISSUE TITLE
Default highlighter is Python

### ISSUE THREAD

**Issue by tucked** [sphinx-contrib/confluencebuilder#1020]
https://github.com/sphinx-contrib/confluencebuilder/blob/48366e6dfcd93d80ba96b43e0fa976687805b4b0/sphinxcontrib/confluencebuilder/std/confluence.py#L408-L414

Hey there, we use this plugin alongside `myst-parser` to publish Markdown to Confluence.
I was wondering/hoping there's a way to make a code fence with no highlighter specified correspond to `{noformat}` on Confluence.
Is that possible?

**Comment by jdknight** [comment]
It is possible to configure the default highlight style using the [`confluence_lang_overrides`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_lang_overrides) configuration. For example, to change from the internal default of `python` to no language (e.g. `none`), the following can be used:

```
confluence_lang_overrides = {
    'default': 'none',
}
```

**Comment by tucked** [comment]
aha! That's great, thank you 👍
