### ISSUE TITLE
Incompatibility with sphinx-toolbox 3.8.0

### ISSUE THREAD

**Issue by adamtheturtle** [sphinx-contrib/confluencebuilder#1029]
When building my docs with the new `sphinx-toolbox` I see:

```
sphinxcontrib/confluencebuilder/transmute/ext_sphinx_toolbox.py", line 85, in replace_sphinx_toolbox_nodes
    new_node.attributes['title'] = node.label
                                   ^^^^^^^^^^
AttributeError: 'CollapseNode' object has no attribute 'label'
```

I believe that this is due to https://github.com/sphinx-toolbox/sphinx-toolbox/commit/ae0ae836268a8e77e36ce58e534131e9ac42a75d.

I can make a minimal reproduction if needed.

**Comment by jdknight** [comment]
Should be handled via https://github.com/sphinx-contrib/confluencebuilder/pull/1030.

Feel free to try it out and report any issues.

**Comment by jdknight** [comment]
v2.7 is now available on PyPI -- marking as closed.

**Comment by adamtheturtle** [comment]
Thank you!
