### ISSUE TITLE
Usage with sphinx.ext.imgmath

### ISSUE THREAD

**Issue by liebsc21** [sphinx-contrib/confluencebuilder#1031]
I want to process LaTex code to images when I push my docs to confluence.

Without `sphinx.ext.imgmath`, the LaTex code is absent in confluence. When I use the extension, I get the following error upon `make confluence`:
```
File ".../site-packages/sphinxcontrib/confluencebuilder/transmute/ext_sphinx_toolbox.py", line 85, in replace_sphinx_toolbox_nodes
    new_node.attributes['title'] = node.label
AttributeError: 'CollapseNode' object has no attribute 'label'
```
Any hints how to sort this out?
I use
- sphinx==7.4.7 and 
- sphinxcontrib-confluencebuilder==2.6.1 in
- python 3.10.

Btw, `make html` with `sphinx.ext.imgmath` works as expected.

**Comment by jdknight** [comment]
https://github.com/sphinx-contrib/confluencebuilder/issues/1029

**Comment by jdknight** [comment]
v2.7 is now available on PyPI -- marking as closed.
