### ISSUE TITLE
Sortable Tables

### ISSUE THREAD

**Issue by GruenSein** [sphinx-contrib/confluencebuilder#1062]
Hi there,
I've been using confluencebuilder lately and have come to appreciate it immensely as it is a lot more practical and reliable than the atlassion-python-api and working with a well-structured rst documentation simply feels superior to dealing with individual API calls that tend to time out regularly. It has become part of my projects pipeline generating dynamically generated documentation and I am very satisfied with it. However, I am wondering if there is a way to generate sortable tables. Confluence offers corresponding macros but the tables generated from rst-files seem to be static only. This would improve the usefulness immensely. Is there a way to achieve this?
Thanks for all the work on this amazing tool!

**Comment by GruenSein** [comment]
Hi @jdknight, thank you for your response. Your suggestion works (see below). The downside of this is that confluence pages with many elements using the "v2" interface are quite slow. This is probably related to confluence and not the builder, though.

Anyway, thanks again!

<img width="431" alt="image" src="https://github.com/user-attachments/assets/78a1f053-5d09-4848-8396-e79ac6877e64">

**Comment by jdknight** [comment]
Sadly, yes -- I wish I could provide a better answer here. Indeed larger pages do render slower when using the newer editor.

The only other suggestion I can give is if the tables you wish to be sorted are on their own pages, you can configure the editor type per page. For example, leaving `confluence_editor` unset and adding the following at the top of a page (rst):

```
.. confluence_metadata::
    :editor: v2
```
