### ISSUE TITLE
autosummary: Add support

### ISSUE THREAD

**Issue by janderil** [sphinx-contrib/confluencebuilder#145]
Now that autodoc is supported, it would be useful to also support the [autosummary](http://www.sphinx-doc.org/en/1.5.1/ext/autosummary.html) extension. This extension is used in automated documentation tools such as [better-apidoc](https://github.com/goerz/better-apidoc) and [automodapi](https://github.com/astropy/sphinx-automodapi).    

I have an initial implementation of this feature: https://github.com/janderil/sphinxcontrib-confluencebuilder/tree/feature/automodapi-support

The changes consist of: 
* adding minimal support for `autosummary_table` and `autosummary_toc` nodes
* adding anchors to the sigantures generated by autodoc so they can be referenced
* modify `_visit_reference_intern_uri` to parse the internal reference (otherwise it generates broken links)

**Comment by jdknight** [comment]
@janderil, thanks for pointing this out. I am all for having this extension support this (from a quick glace at what it does). Unfortunately, I will not be able to commit any implementation time to this at this moment (any time I can get will first be going to cleanup work for next release, improved autodoc support (more test samples any respective corrections) and then math support).

If you want to continue your own development on this (or leave what you have initially as is), that works for me; contributions are welcome. Please make sure that anything you wish to introduce should follow [CONTRIBUTING.rst](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/blob/master/CONTRIBUTING.rst) -- specifically, I notice that your commits do not have sign-offs. Anything you want to have reviewed, I am more than willing to look over any code.

**Comment by jdknight** [comment]
Support for the `sphinx.ext.autosummary` extension is now available on `master` from the changes introduced in #257. I will be flagged issue as "pending next release" and will close on the next stable release (unless there is a problem observed on `master` related to this issue).
