### ISSUE TITLE
:meth: not working

### ISSUE THREAD

**Issue by Ghodot** [sphinx-contrib/confluencebuilder#146]
Hello !

In a module, I'm trying to reference a method from another module using the full path to the method :
`:meth:my_package.sub_package.module.class.method`.

It works when I use `make html`, but when I try to use `make confluence` I see : 
`WARNING: unable to build link to document due to missing title (in docs/my_package.other_sub_package.other_module): docs/my_package.sub_package.module.conf#my_package.sub_package.module.class`

I tried adding titles at various places but it didn't change the issue

**Comment by jdknight** [comment]
I suspect this is the same issue mentioned in #147 (from #144). While this could be marked as a duplicate, I would be nice to add a specific test case which validates the use of `:meth:`, so maybe this issue can be left open until this is done.

@Ghodot, if you feel this is not the case, please feel free to indicate so.

**Comment by Ashkeelun** [comment]
I believe I've run into a similar issue with the :attr: reference in version 1.1.0 of the confluencebuilder. Looking into the pages generated neither the methods nor attributes of a class contain generated anchors, however the reference link is generated but can't go anywhere.

I haven't yet checked if the next release fixes this issue or not, but from what I was reading this seemed unrelated to the table of contents linking issue described in #144 and #197 but I could be wrong.

**Comment by jdknight** [comment]
With the merge of #271 onto `master`, it appears that both method and attribute references appear to be working now. The next stable release (v1.2) should include support for this.

Thanks for the information; it is always appreciated.
