### ISSUE TITLE
mermaid.js support

### ISSUE THREAD

**Issue by gshiva** [sphinx-contrib/confluencebuilder#159]
It would great if https://mermaidjs.github.io/ can be added.

https://github.com/mgaitan/sphinxcontrib-mermaid 

works fine so far.

Thanks

**Comment by jdknight** [comment]
I wonder if this extension may also "just work" on `master` (in a similar fashion as discussed in [158#issuecomment-449601516](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/issues/158#issuecomment-449601516)). Will mark as "investigation" and attempt to test it along side #158.

**Comment by jdknight** [comment]
Taking a more in-depth look at the `sphinxcontrib-mermaid` extension and `mermaid.js` library, neither appears to justify adding implementation into this extension. The following outlines the current state for handling either a "raw" format type or a "png"/"svg" format types.

To take advantage of mermaid "raw" diagrams, the mermaid Javascript asset needs to be registered on the target Confluence instance -- something that this extension (nor non-administrators) cannot do for an instance (without considering the corner case of when the HTML macro may be available). Considering the case where an instance is configured for support, while this extension could just add a `mermaid` node handler to generate a raw type, this would be better to manage outside this extension (see #198 for more details). There would also be doubt into whether or not Confluence will allow adding a classname on a div-container for mermaid to take advantage of (although it may just work).

As for image-specific format (e.g. "png"), there was the hope that it would "just work" when this extension added support to publish images. After inspecting how `sphinxcontrib-mermaid` generates images, there is not a simple integration between the two extensions. When a documentation is configured for output to "png", `sphinxcontrib-mermaid` performs the conversion (using `mmdc`) at the builder phase -- and this conversion/output only applies to the internal builder's which the `sphinxcontrib-mermaid` extension explicitly implements (the standard extensions). It would have been nice if the mermaid extension instead, when using a file output type, to use a transform  which translates `mermaid` nodes to `image` nodes with references to the newly generated images. This would allow the `confluence` builder to automatically use the images with no additional work.

Based on the above information, this issue will be closed.
