### ISSUE TITLE
lack of multi-page navigation

### ISSUE THREAD

**Issue by n2ygk** [sphinx-contrib/confluencebuilder#166]
Multi-page sphinx documents when rendered in Confluence do not have the Previous and Next page navigation links (am I missing a configuration setting?) nor is it possible to have a sidebar ToC to support in-page navigation (Confluence [limitation](https://jira.atlassian.com/browse/CONFSERVER-43090)). I have documented the concerns more fully [here on RtD](https://columbia-it-django-jsonapi-training.readthedocs.io/en/latest/sphinx.html#confluencebuilder-shortcomings) and [here in Confluence](https://confluence.columbia.edu/confluence/display/~alansphinx/Sphinx+Documentation#SphinxDocumentation-Confluencebuildershortcomings) in the actual sphinx doc that I used to test confluencbuilder. (Thanks to @jdknight for fixing one of the issues I hit with curly-braces in headings being interpreted as macros -- see #161).

If you were able to get navigation links working, that would somewhat mitigate the Confluence sidebar ToC limitation. If Atlassian were to fix [#43090](https://jira.atlassian.com/browse/CONFSERVER-43090) that would be huge.

**Comment by n2ygk** [comment]
@jdknight actually, it seems "next" and "previous" should be pretty easy without a custom macro just using links to pages. I've added a couple manually just to demonstrate: https://confluence.columbia.edu/confluence/display/~alansphinx/Using+the+Django+REST+Framework+and+DRF-JSONAPI 

The comparable thing generated by sphinx for html is `<link rel="next" title="Welcome and Caveat" href="welcome.html" />`.

**Comment by jdknight** [comment]
@n2ygk, if a user wishes to manually place "next"/"previous" links within their own documentation, this is a possible path. A user would know the order of which the documents will be, references added in the restructuredText will be converted to respective links for Confluence and the user can manually adjust sorting (if desired) in the space which the documents have been published to.

However, I was under the assumption that you wanted the builder to automatically generate these links for the resulting pages (in a similar fashion how the HTML builder works). Assuming that the order of processed documents is the desired order for pages during Sphinx generation, there will still be an inconsistency between how Confluences orders the pages in its navigation panel to the order of the links on the individual pages. I believe that Confluence will order pages lexicographically first. Assuming a documentation set at the following building/publishing order:

- Index
- Appendix
- Content

And there existed a feature in this extension to have "Index" have a next-link to "Content", and "Content" have a next-link to "Appendix", Confluence will list in its navigational panel the following order:

- Appendix
- Content
- Index

I feel this is a navigational inconsistency. Another use case to consider is how pages on a space can be manually ordered. If a user moves a page with the re-order option:

![image](https://user-images.githubusercontent.com/1834509/51300603-85decb80-19fa-11e9-9a23-e06d9114761f.png)

Or if a user manually orders a page using the drag-and-drop capability:

![image](https://user-images.githubusercontent.com/1834509/51300608-8bd4ac80-19fa-11e9-9ee1-e81ff2ead983.png)

This can result in the same navigational inconsistency as mentioned in the first example. These are the main reasons why such a feature was not specifically sought out.

That all being said, there could be a way to bring such a capability as long as such a features explicitly indicates the caveats with respect to ordering and does not conflict with prospect ordering work outlined in #164. If we rely on the order that Sphinx will process a documentation set and inform users that they would need to manually adjust the ordering of pages for a navigational consistency, then this may be fine. Page updates to a space will not override any ordering set by the user, so a publisher only needs to worry about new pages. I assume this might be a non-trivial task for documentation sets consistent of hundreds of pages. It might be best if such a capability is introduced that said capability be listed as advanced/experimental.

Other notables to consider with this feature:
- Dealing with empty content pages.
- Ensure next/previous links work while [`confluence_max_doc_depth`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-max-doc-depth) is being used.

**Comment by jdknight** [comment]
(see also #214)

**Comment by jdknight** [comment]
The initial implementation for next/previous pages have been merged into master (see #214) and will be available next release.
