### ISSUE TITLE
recommentation: dco github application integration

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#182]
I would like to suggestion the inclusion of the following GitHub application be added to this repository:

> Developer Certificate of Origin
> https://probot.github.io/apps/dco/

With the option of "Require signed commits" enabled:

![image](https://user-images.githubusercontent.com/1834509/53683912-ad50d580-3cd4-11e9-912f-08c71356a38b.png)

**Comment by tonybaloney** [comment]
👍

**Comment by jdknight** [comment]
@stephenfin, (at'ing you since you have helped deal with this stuff before; if there is an alternative approach I would be using instead to make such an inquiry, I would be curious to know).

Is there a way to have the application mentioned in this issue registered to this repository?

**Comment by stephenfin** [comment]
That's installed now. In general, I'm not sure if/how admins of projects within an organization can install these. Maybe request access so I can approve it?

**Comment by jdknight** [comment]
@stephenfin, thanks! OK, learnt something today. As a member, I did have an option to request the installation of the application:

![image](https://user-images.githubusercontent.com/1834509/59729200-5b907480-920b-11e9-85ed-4fe48a87a827.png)

Which I assume in turn an administrator such as yourself could approve it. It currently says it is installed (i.e. I do not have the option to request it) so I believe your changes have done everything needed to be done. Maybe on a next pull request change, the trigger check will perform the respective DCO check.

**Comment by jdknight** [comment]
DCO application is working as expected; marking this issue as closed.
