### ISSUE TITLE
discussion: thoughts on transferring into sphinx-contrib

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#183]
@tonybaloney, curious if you have any opinions of possibly transferring this repository into the @sphinx-contrib organization \[1\]. I believe there can be advantages in moving (visibility, better chance for more maintainers, etc.). Although, if you prefer to leave the repository in its current location, that is fine by me and this issue can be closed.

\[1\]: https://groups.google.com/forum/#!topic/sphinx-dev/y_1LgQgD_Ro

**Comment by tonybaloney** [comment]
this is a great idea

**Comment by tonybaloney** [comment]
@jdknight in the meantime can you check if you can merge pull requests now?

**Comment by jdknight** [comment]
> @jdknight in the meantime can you check if you can merge pull requests now?

Confirmed; with the peer review requirement disabled, I now have the ability to merge in my own requests (assuming that is what you are looking for).

> this is a great idea

I assume you are for the [transferring a repository](https://help.github.com/en/articles/transferring-a-repository) (to move all the active pull requests, issues, etc.) based on this commit.

@stephenfin (pulled your name from the group and matched it to the sphinx-dev Google group), would you be able to assist in this matter (if sphinx-contrib still likes to be a container for these projects and does not mind the inclusion of the sphinxcontrib-confluencebuilder project)? I suspect once a repository transfer can be made, the end goal would be to still have @tonybaloney and myself (@jdknight) with access to manage the repository (assuming that is how the sphinx-contrib organization works).

**Comment by stephenfin** [comment]
I've invited you both to the organization. This should let you transfer the project. Ping me if you've any issues doing so.

**Comment by tonybaloney** [comment]
Done! thanks @stephenfin @jdknight

**Comment by tonybaloney** [comment]
@stephenfin please can you setup a team where @jdknight and I have maintainer control over this repo (merge, close, tag, etc.)

**Comment by stephenfin** [comment]
The original owner of the repo should have maintainer rights, including the ability to add new maintainers. If that's not the case, let me know and I can manually add people (or explore teams, as you suggest)

**Comment by tonybaloney** [comment]
@jdknight do you have control to merge PR's etc now?

**Comment by jdknight** [comment]
@tonybaloney looks good on my end.

**Comment by stephenfin** [comment]
It's a nit, but if possible could you drop the `sphinxcontrib-` prefix from the project name (though not the package name, obviously)? It's superfluous given the organisation name :smile:

**Comment by tonybaloney** [comment]
> It's a nit, but if possible could you drop the `sphinxcontrib-` prefix from the project name (though not the package name, obviously)? It's superfluous given the organisation name 😄

In the GitHub project name? The pypi package name would remain the same.

**Comment by stephenfin** [comment]
Correct. Keep the package name as-is but switch `sphinx-contrib/sphinxcontrib-confluencebuilder` to `sphinx-contrib/confluencebuilder`. Just a nit thought

**Comment by tonybaloney** [comment]
> Correct. Keep the package name as-is but switch `sphinx-contrib/sphinxcontrib-confluencebuilder` to `sphinx-contrib/confluencebuilder`. Just a nit though

@stephenfin i agree, I can’t make the change though. only the org admin can do that.

**Comment by stephenfin** [comment]
Ah, if you're ok with me doing that, I can do so

**Comment by tonybaloney** [comment]
@stephenfin 👍 from me and @jdknight

**Comment by tonybaloney** [comment]
(that's all you need :-))

**Comment by stephenfin** [comment]
Done and done. Thanks, both. I guess this can be closed now?

**Comment by jdknight** [comment]
I believe so. Thanks @stephenfin for the help; thanks @tonybaloney for promoting the move.
