### ISSUE TITLE
update repository description

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#193]
This repository's description is out-of-date since this extension generated storage format documents instead of Confluence wiki-styled format documents. It is recommended to update the description of this repository from "A confluence wiki markup builder plugin for Sphinx" to "Confluence Storage Markup Builder Plugin for Sphinx" (or any other preferred description that includes the correction).

**Comment by jdknight** [comment]
@stephenfin, any chance you are able to update this project's description to the follow?

```
Confluence Storage Markup Builder Plugin for Sphinx
```

(since I assume this requires owner access)

**Comment by stephenfin** [comment]
This is done now. I've also added both of you with the Maintainer role, which seems like it should allow you to do this going forward.
