### ISSUE TITLE
Filename of download file

### ISSUE THREAD

**Issue by ErikRtvl** [sphinx-contrib/confluencebuilder#194]
I am using the :download: directive to add a downloadable file. The file is being uploaded, but the filename appears incorrectly. When I use:

```
:download:`filename <../../../filename>`
```

The filename in confluence comes up as

`..__..__..__filename`

Instead of just "filename".

Anything I am doing wrong? Or is this an issue to be solved?

Python version 3.5.4, sphinx 1.7.9, confluencebuilder master branch, approx. one month ago.

**Comment by jdknight** [comment]
The snippet you have provided _should_ work. I will try to spawn up an environment with the same versions and see if I can reproduce the issue. Are you using Confluence Cloud or Confluence Server? And if server, which version?

I know our validation tests do attempt to support a label for a file reference ([download.rst][1]/[v1.1-download][2]). I wonder if the issue (with the extension) is that it is not properly handling the relative path (although, I do not know why off hand why that would be the case).

[1]: https://github.com/sphinx-contrib/confluencebuilder/blame/master/test/validation-sets/common/download.rst#L26-L27
[2]: https://jdknight.atlassian.net/wiki/spaces/confluencebuilder/pages/813334750/v1.1-download

**Comment by ErikRtvl** [comment]
Sorry for not getting back to you earlier; got busy with another project. However, we using a confluence server, version 6.14.3.

I seems to happen only for files that are not in the source directory of the documentation (where conf.py is). In the source directory, I also have a example/example.zip which uploads just fine.

I also tried an absolute path as well, but the result, unfortunately, is the same.

**Comment by ErikRtvl** [comment]
A small update;  I just noticed that the file uploaded to Confluence actually always includes the folder structure by prepending the folder names separated by underscores. Also for examples/example.zip, which is downloaded later as examples_example.zip.

When using a html-build, the filenames end up just fine. I tried reading your code but it doesn't shed any light on the issue to me (I do not understand the inner workings of sphinx well enough). Could it be that the uploading system is trying to create a similar folder structure to the one in the download directive, and confluence does not allow this but alternatively creates the shown filename structure?

**Comment by jdknight** [comment]
Most likely an issue with [`interpretAssetKeyPath`](https://github.com/sphinx-contrib/confluencebuilder/blob/2dc6319f6268f44e7f7cf2625a41c45a1c948a05/sphinxcontrib/confluencebuilder/assets.py#L215). As you have mentioned, the lazy key value for an asset will based off the full path of the asset with unsupported characters replaced with underscores. This is a crude way of having "unique" assets and managing them across different documents. There should be a better way to determine a proper "key" for an asset (dealing with various relative paths, duplicate assets and duplicate naming (resolving a consistent fallback name when document order processing can change).

Maybe a simple approach would be something such as:
1) Use just the basename of the asset to be published if no duplicates exist.
2) If two or more assets have the same name, use the hash of the asset instead (assuming they are not the same file).

**Comment by jdknight** [comment]
With the introduction of #228 into `master`, I believe this issue has been addressed. Additional testing will be performed on various Confluence revisions before next release for additional verification, but for now, flagging this issue as pending-next-release.
