### ISSUE TITLE
Support for sphinx.ext.todo

### ISSUE THREAD

**Issue by mariof67** [sphinx-contrib/confluencebuilder#196]
Thanks for writing the excellent confluence builder extension!

I ran into an issue: When I use sphinx.ext.todo with the confluence builder, I get an error:

Exception occurred:
  File "/home/mferriz/PycharmProjects/venv/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/translator.py", line 132, in unknown_visit
    raise NotImplementedError('unknown node: ' + node.__class__.__name__)
NotImplementedError: unknown node: todo_node

About my environment:

Sphinx version: 2.0.1
Python version: 3.6.7 (CPython)
Docutils version: 0.14 
Jinja2 version: 2.10.1
Confluence Builder: 1.1.0

To get past this error, I either need to remove the extension sphinx.ext.todo, or set todo_include_todos to False.

Please advise. Thanks!

**Comment by jdknight** [comment]
While `sphinx.ext.todo` is an extension which is currently not supported by this extension yet, it is part of Sphinx's embedded extensions and is "allowed" to be implemented inside this extension (in a similar matter as [`autodocs` is supported](https://github.com/sphinx-contrib/confluencebuilder/blob/master/sphinxcontrib/confluencebuilder/translator.py#L1335-L1337)). I may be able to add support this extension in the future (unless anyone else gets to it first). Note that there are currently a series of bugs noted in the issue tracker which will take priority at this time.

**Comment by jdknight** [comment]
This issue should be addressed in #220 and will be available next release (available now on `master`).
