### ISSUE TITLE
Mixture of path separators causes broken links

### ISSUE THREAD

**Issue by mwmattis** [sphinx-contrib/confluencebuilder#197]
Hello.
I found an issue similar to https://github.com/sphinx-contrib/confluencebuilder/issues/144.
All links in an toctree which are not on the top level page raise

> WARNING: unable to build link to document due to missing title ...

I found that ```ConfluenceTranslator.docname``` contained backslashes as path separator only, this is why the check here always fails for me: https://github.com/sphinx-contrib/confluencebuilder/blob/master/sphinxcontrib/confluencebuilder/translator.py#L50

My environment is Windows 10, Pypy 5.8 (Python2.7), Sphinx 1.8.4 and sphinxcontrib-confluencebuilder-1.1.0

I have fixed this by converting the path in ```ConfluenceTranslator.docname``` to an OS-independent form. See https://github.com/mwmattis/confluencebuilder/commit/6cb48803fbb2dda927465303f7d5f29f5ba32dd5

If this makes sense, I could create a pull request.

Best regards

**Comment by loritzm** [comment]
I've come across the same problem, building on Windows/CPython3.6/Sphinx 2.0.2 while using forward slashes as path separator. Applying the change from your mentioned commit fixed this.

I was puzzled somewhat as I'd thought this to be quite a common setup, although using path2doc seems to have been introduced only quite recently. Nevertheless, it'd be nice to know whether the change in [5a6e5f6](https://github.com/sphinx-contrib/confluencebuilder/commit/5a6e5f68529d9c07c89de5be486b2768416f33c1) has also been tested on Windows and with nested structures.
@jdknight: Can you remember about that?

**Comment by jdknight** [comment]
Yup ~ for sure an issue. Thanks for the report.  This has also later been reported in #200 which has already queued up a pull request #201 which appears to have the same contents; but is signed + has a test case. Will most likely continue effort to resolving this issue through that pull request, unless someone has any comment on the matter.

**Comment by jdknight** [comment]
Thanks everyone for the report and pull request (@verdesmarald). A fix has been merged in and available on `master`. This fix should be made available on PyPI next stable release (v1.2). Will mark as closed.
