### ISSUE TITLE
Support for Jupyter Notebooks

### ISSUE THREAD

**Issue by Riezebos** [sphinx-contrib/confluencebuilder#198]
I was trying to use confluencebuilder together with nbsphinx. Initially I got errors about not implemented node types. I don't know a lot about sphinx but after adding the following methods to the ConfluenceTranslator class it started working:

```
    def visit_CodeAreaNode(self, node):
        pass

    def depart_CodeAreaNode(self, node):
        pass

    def visit_FancyOutputNode(self, node):
        pass

    def depart_FancyOutputNode(self, node):
        pass

    def visit_AdmonitionNode(self, node):
        pass

    def depart_AdmonitionNode(self, node):
        pass
```

The code cells of my notebook are nicely shown in confluence, but the output is missing (except for a picture). This is an example of how it looks in HTML:
https://nbsphinx.readthedocs.io/en/0.4.2/code-cells.html

Would you like to have support for Jupyter Notebooks as a feature? Would it be a lot of work to implement? Should I try to do it myself and/or ask the nbsphinx team instead of you?

**Comment by jdknight** [comment]
There was a [similar conversation][1] which has been discussed before (if interested). I made a comment outlining some initial thoughts on different methods on having other extensions wishing to contribute to a Confluence output along with this extension were made. Instead of just speculating on the best approach, I decided to try to find what a "proper" solution would be for a case such as this. From what I have seen (which still may be incorrect since I am not a Sphinx/docutils expert), is that it is best that such a modification would be best implemented outside of nbsphinx's or this extensions main repository. Instead, a separate extension could be made which understands both extensions and can inject proper output into the Confluence Builder's translator.

The following repository shows a minimal example on how this could be achieved:

> sphinx-confluence-nbsphinx-test
> https://github.com/jdknight/sphinx-confluence-nbsphinx-test

With a new extension registered into the list:

```
extensions = [
    'nbsphinx',
    'sphinxcontrib.confluencebuilder',
    'sphinxcontrib.confluencebuilder_nbsphinx',
]
```

The extension can register the custom node type and define the visit/depart methods for Confluence. For example, if there was a desire to support a custom node type, a node `CustomNode` can be supported as follows:

```
def visit_CustomNode(self, node):
    pass
    
def depart_CustomNode(self, node):
    pass

def setup(app):
    ...
    app.add_node(CustomNode, confluence=
        (visit_CustomNode, depart_CustomNode), override=True)
    ...
```

So, in a simple answer: no, I do not believe it would be proper that this extension would include this implementation. That being said, there is always room to discuss the possibility to adjust aspects of this extension to allow other extensions to easily contribute to the output of a Sphinx Confluence document.

[1]: https://github.com/sphinx-contrib/confluencebuilder/pull/114#issuecomment-478954869

**Comment by jdknight** [comment]
On a related note, when testing around with the same documentation from `nbsphinx`, I do see some oddities in at least Confluence Cloud. For the output (as mentioned in the original comment), the content does not appear to render. When looking at the Sphinx HTML output of the document, the following is rendered:

![image](https://user-images.githubusercontent.com/1834509/59729798-1588e000-920e-11e9-91f3-7070a25b2161.png)

With the same document processed with this extension, the output does not appear to be rendered:

![image](https://user-images.githubusercontent.com/1834509/59729882-3e10da00-920e-11e9-9bcc-e179ff16c422.png)

However, when inspecting the sources (even shown on the uploaded document on the Confluence instance), shows that the code block has the desired content:

```
<p>A simple output:</p>
<ac:structured-macro ac:name="code" ac:schema-version="1" ac:macro-id="ca27846c-16f4-484e-be16-559cb5be45c8"><ac:parameter ac:name="language">python</ac:parameter><ac:parameter ac:name="linenumbers">false</ac:parameter><ac:plain-text-body><![CDATA[6 * 7]]></ac:plain-text-body></ac:structured-macro>
<ac:structured-macro ac:name="code" ac:schema-version="1" ac:macro-id="d2311ce5-f85f-497c-bc1f-a09e8fc4cfc0"><ac:parameter ac:name="language">none</ac:parameter><ac:parameter ac:name="linenumbers">false</ac:parameter><ac:plain-text-body><![CDATA[42]]></ac:plain-text-body></ac:structured-macro>
```

Moving into edit mode, the desired output is shown:

![image](https://user-images.githubusercontent.com/1834509/59729944-7f08ee80-920e-11e9-8343-76862402ad2f.png)

When exporting the same document to a PDF, the desired output is shown:

![image](https://user-images.githubusercontent.com/1834509/59730017-c42d2080-920e-11e9-8dbd-888baf40e405.png)

It looks to me like there is a Confluence issue here. I do see [CONFCLOUD-61941](https://jira.atlassian.com/browse/CONFCLOUD-61941); however, it is listed as fixed. But manually adding or removing a character to make it a non-two-character sized CDATA makes it render... :expressionless:

**Comment by Riezebos** [comment]
Thanks for looking into it! Your answer makes sense, I hadn't thought of it that way.

The confluence issue is listed as "Resolved" but the resolution is "Won't fix" because of a new editor that is supposedly going to improve everything for everyone. 

This new editing experience also says it has full markdown support so that could make it a lot easier to integrate with other formats and tools.

For my specific problem the current solution is using readthedocs instead of confluence, which looks a lot nicer as well. If I ever want to retry hosting docs on confluence I'll be sure to try out your solution!

**Comment by planetmarshall** [comment]
@jdknight I was having another look at this today, I am having the same issue (output cells not being rendered), however the cells are **not** being rendered by the builder - I get

```
<ac:structured-macro ac:name="code">
<ac:parameter ac:name="language">none</ac:parameter>
<ac:parameter ac:name="linenumbers">false</ac:parameter>
<ac:plain-text-body><![CDATA[6 * 7]]></ac:plain-text-body>
</ac:structured-macro>
```

for the notebook output.

However, the output is definitely being generated, as it triggers a call to `visit_CodeAreaNode`.

Many thanks for your work on this by the way.

**Comment by jdknight** [comment]
@planetmarshall, just want to understand your question a bit more. You mention you have the following in the generated documentation:

```
<ac:structured-macro ac:name="code">
<ac:parameter ac:name="language">none</ac:parameter>
<ac:parameter ac:name="linenumbers">false</ac:parameter>
<ac:plain-text-body><![CDATA[6 * 7]]></ac:plain-text-body>
</ac:structured-macro>
```

Are you saying that the code block with the contents "6 * 7" is not being rendered? Or is it that the desired trailing output of "42" is not being shown?

I would be curious to know if it was the former. Using the exact contents and pushing it to Confluence, it does render on a Confluence Cloud instance for me:

![image](https://user-images.githubusercontent.com/1834509/144756041-d6ed55f6-771e-49b4-87d4-be7897910af1.png)

If it does not render for you, Could you indicate which version of Confluence and browser you may be using?

However, if it is the latter issue (i.e. "42" is not showing), this would still be [the issue mentioned in the above comment](https://github.com/sphinx-contrib/confluencebuilder/issues/198#issuecomment-503370013). Atlassian still has not fixed an issue of rendering a two-character code block. If this is what you are experience, you can try to go to [CONFCLOUD-61941](https://jira.atlassian.com/browse/CONFCLOUD-61941) to vote on re-opening the issue; or trying to push for its consideration through your Atlassian support representative (if you are using a paid account).

**Comment by planetmarshall** [comment]
Sorry let me clarify - the output I posted is what is generated by confluence builder, ie by just putting a print statement in `confluencebuilder.writer.translate`. This is before it is ever rendered by confluence.

However - I can see the following data being processed by `visit_codeAreaNode`:
```
<CodeAreaNode prompt="[1]:" stderr="False"><container classes="output_area "><raw classes="highlight" format="html" xml:space="preserve"><pre>
42
</pre></raw><raw format="latex" xml:space="preserve">\begin{sphinxVerbatim}[commandchars=\\\{\}]
42
\end{sphinxVerbatim}</raw></container></CodeAreaNode>
```

But it doesn't end up in the builder output.

**Comment by planetmarshall** [comment]
I think I see the issue - The input `CodeAreaNode` has a child `literal_block` which is parsed by the translator, but the child of the output `CodeAreaNode` is a `raw` node rather than a `literal_block`, so appears to be skipped.

**Comment by jdknight** [comment]
Ah -- I understand now, thanks for the information.

At this time, it would be correct to say that this extension does not support nbsphinx. Although, we have relaxed the restriction of not supporting third-party extensions in this extension (if it's just simple binding/etc. things) -- so we can take a look at trying to improve support for it.

The raw output you have provided (as you have already described the issue) is that it looks like nbsphinx is generating raw node blocks for the contents of their `CodeAreaNode`. The Confluence builder extension does not accept either the `html` or `latex` format types (although, you could try setting `confluence_adv_permit_raw_html = True` for some unsupported workarounds).

Typically, if support was added, the general approach would be converting `AdmonitionNode` nodes to docutils admonition nodes; and `CodeAreaNode` nodes to docutils literal nodes; which in turn, the Confluence builder extension will process them. Without looking diving into anything yet -- I assume the `FancyOutputNode` node would also be similar to replacing them to be docutils literal nodes as well.

**Comment by planetmarshall** [comment]
@jdknight Thanks. I've made a first stab at this using your test project as a template. It's not the prettiest but all the content is present. It would be nice to be able to display the IPython prompt in some way.

https://github.com/planetmarshall/sphinx-confluence-nbsphinx-test

![Screenshot from 2021-12-06 11-51-17](https://user-images.githubusercontent.com/422117/144841328-197bc984-9d30-4ae2-bcbc-4682064ab5a2.png)
