### ISSUE TITLE
Unit tests fail due to changes in Sphinx 2

### ISSUE THREAD

**Issue by verdesmarald** [sphinx-contrib/confluencebuilder#202]
There are at least 2 breaking changes in Sphinx 2 that cause unit test failures:

1. The default value for `master_doc` is now `index` rather than `contents`. This causes one test to fail and several other tests to emit a warning (`WARNING: Since v2.0, Sphinx uses "index" as master_doc by default. Please add "master_doc = 'contents'" to your conf.py.`). This can be easily fixed by adding `config['master_doc'] = 'contents'` to the `prepareConfiguration` method.
1. The default alignment for tables and figures is now centered instead of left. This causes one of the tests to fail because it contains a figure with no `:align:` property. This is more difficult to fix since the tests currently don't cater for differing output depending on the Sphinx version being used.

**Comment by jdknight** [comment]
@verdesmarald, thanks for the notice. With #204 merged in, hopefully this puts this extension in a better state with the most recent (stable) Sphinx release. Will mark as closed.
