### ISSUE TITLE
discussion | prospect changes 2019a

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#208]
@tonybaloney, I have been thinking about a series of small changes or goals related to this extension and I was wondering if you would be willing to provide some feedback on the following:

1) An unofficial rule for this extension is to only support Confluence editions which are currently supported by Atlassian (while features/fixes can remain inside the implementation to support legacy versions, said implementation is free to be removed when affecting continued maintenance of this extension). Any objection to listing this as an "official rule"?

2) I have a personal goal which aims to support at least the last 5 major revision trees of Sphinx (e.g. current Sphinx has v2.1; thus v1.6, v1.7, v1.8, v2.0 and v2.1 are "supported"). If there is a future major/minor revision to Sphinx, I would feel that the oldest revision (in the same example, revision v1.6), would be dropped from official support of this extension. Is this acceptable?

3) This repository current maintains a `AUTHORS` to track contributors to this repository; however, I feel that content is no necessarily needed as this information can easily be obtained through Git-provided capabilities. Therefore, I would like to propose that this document be dropped. The primary goal here is to remove the maintenance required on the `AUTHORS` document. If the document is preferred, I do not mind leaving it as is (and continued updates when external contributors participate). Along with this change, a common header template for source files could be changed to the following:
```
# -*- coding: utf-8 -*-
"""
    :copyright: Copyright YYYY[-YYYY] by Sphinx Confluence Builder
    :license: BSD-2-Clause, see LICENSE for details.
"""
```

4) Removal of `setup.cfg` (i.e. bumpversion configuration). I am not a particular fan of the (obsolete) bumpversion package and have no strong desire to switch to bump2version. Primarily since there is not much content to change when a release version is made (i.e. two files). Any objection remove this configuration file? Or is there something else you would prefer?

5) Renaming of `requirements_dev.txt` to `requirements.txt`. I am not exactly sure why the requirements file includes the `_dev` post-fix, so I am hoping to remove it (and update respective tox configuration files). If there is a reason why this should not happen, I would be curious to know.

6) Renaming `doc` to `Documentation`. I have a personal preference to house documentation content in a folder named `Documentation` (to match the similar style observed by the Linux Kernel). Any objections to the change?

7) Deprecating XML-RPC support next revision and dropping support the subsequent revision (or two). While initially the lifeline protocol for this extension, I doubt many users still use XML-RPC (I believe in Confluence installations, the capability is not enabled by default; and may not be available on Confluence Cloud). Considering all supported versions of Confluence for this extension includes REST support, it may be a good time to start fading from still supporting this. It could help minimize some implementation and future maintenance tasks.

8) Dropping Python v3.4 support. I arbitrarily assume that individuals using this extension do not specifically use Python v3.4 -- and that fact that Python v3.4 has reached EOL three months ago, maybe it is fine to remove it from the tox/Travis CI configurations (i.e. removing the requirement to have next release be officially supported on Python v3.4). On that note, I know Python v2.7 will be flagged as EOL in 2020; however, I would prefer is some level of support was maintained for at least 3-6 months after the EOL timestamp (since RHEL 7's default is v2.7 and RHEL 8 (defaulting to v3.6) only become generally available a few months ago).

---

Any points agreed upon, I can update the `CONTRIBUTING.rst` with the respective information (where applicable).

Others are free to comment as well.

**Comment by tonybaloney** [comment]
1. Agreed, this should be official
2. Agreed, there is no major reason for people to pin versions of Sphinx other than for plugin compatibility
3. Document not preferred, I like to credit contributors somewhere, not just in the GitHub contributor graph though. If there is another way this can be done? There are some tools to auto-generate release notes?
4. Agreed, can be removed. I'm using pyproject.toml for some of my other projects these days
5. `requirements_dev.txt` is an unofficial convention to say these are the requirements to develop the package (not just use it). These are typically a longer set of requirements than the ones in setup.py
6. I prefer `doc` or `docs`, which are also more common for Python packages, `Documentation` is more common for C and Java apps. 
7. Agreed. 
8. Agreed.

**Comment by jdknight** [comment]
Thanks for the comments.

> 3. Document not preferred, I like to credit contributors somewhere, not just in the GitHub contributor graph though. If there is another way this can be done? There are some tools to auto-generate release notes?

I am not sure. If you prefer to maintain a contributors credit someplace, I would think the existing `AUTHORS` document is still the best place to hold this information. I would most likely not be a personal fan of holding the information inside something like the `CHANGES.rst` file. Maybe if we have individual changelog documents per release version (although I find there are pros and cons of having a single document for easy key change tracking and multiple documents for scalability of change documents).

While I do use Git related logging commands to help pull out authors to check and populate `AUTHORS`, I would also be mixed to just automatically generate this list of contributors ~ solely if there are individuals who may wish to exclude their information from the document (even though the same information can be viewable via Git commit information).

With that all said, I am thinking I will just continue populate `AUTHORS` as normal until a time (if ever) where an alternative method is decided.

> 5. `requirements_dev.txt` is an unofficial convention to say these are the requirements to develop the package (not just use it). These are typically a longer set of requirements than the ones in setup.py

Just for clarification on this point. Are you stating that the existing requirements file could be changed or not (I suspsect the former)? With the existing packages inside this file list components required to be used for extension -- but at the same time, only `tox` uses that file for various testing scenarios (i.e. not required to produce a final package). 

> 6. I prefer `doc` or `docs`, which are also more common for Python packages, `Documentation` is more common for C and Java apps.

Noted; works for me. :)

**Comment by tonybaloney** [comment]
Checkout tools like https://github.com/CookPete/auto-changelog

**Comment by jdknight** [comment]
I am under the assumption that all of the inquiries brought up in this issue have been addressed (either with changes, confirmations, etc.). Marking as closed.
