### ISSUE TITLE
confluence_publish_subset parameters always ends up in a collection of Unicode

### ISSUE THREAD

**Issue by jjcaballero** [sphinx-contrib/confluencebuilder#218]
Hi,

I am using the approach explained in the Tips section from the documentation to set the parameter confluence_publish_subset. But I always get the same error:

_WARNING: 'confluence_publish_subset' should be a collection of strings__

The subset list always ends up in list of Unicode elements. But I have checked it and the value I am using is a collection of strings. Trying to figure out the reason, I have seen sphinx is decoding all overriding parameters and therefore they become Unicode.

sphinx/cmd/build.py

```
235  	        locale = __import__('locale')  # due to submodule of the same name
236  	        likely_encoding = locale.getpreferredencoding()
...

268                  if likely_encoding and isinstance(val, binary_type):
269                  try:    
270                       val = val.decode(likely_encoding)
...
```

Then, in sphinxcontrib/confluencebuilder/config.py, the error is raised because all given files have been modified to be Unicode by sphinx. Has anyone ever experienced such a thing? Should the extension allow also a collection of Unicode? 
The _preferredencoding_ value guessed by locale is "ISO-8859-1". I have tried in another machine whit value "UTF-8" and the same situation/error happens.

- Python: 2.7.13
- Sphinx: 1.8.5
- sphinxcontrib_confluencebuilder:  master

I would appreciate any guideline. And if allowing a collection of Unicode is an acceptable solution, I will be happy to do it myself.

Thanks!

**Comment by jdknight** [comment]
@jjcaballero, sorry for the delay. Had some time to check this out and was able to easily repeat the situation. The configuration option when running under Python 2.x should have still supported Unicode strings, but the crude configuration check did not gracefully support this.

I have made a correction to handle this issue in #218. Feel free to try this out and comment (if desired). This change should eventually be put into `master` and be available next release (I can update this issue to reflect when this has been done). If this change does not address your issue, feel free to mention so.

**Comment by jjcaballero** [comment]
@jdknight no problem. Indeed, this solves my issue too. Thanks for that!

**Comment by jdknight** [comment]
This issue has been addressed in `master` and should be made available next stable release on PyPI.
