### ISSUE TITLE
Add support for use with sphinxcontrib-httpdomain extension

### ISSUE THREAD

**Issue by rite2hhh** [sphinx-contrib/confluencebuilder#223]
I tried using the `confluencebuilder` extension with `httpdomain` extension and it fails. Not entirely sure if it's supported, and broken, or the use of the two extensions together is not supported yet.

Traceback written to the sphinx log file:
```
# Sphinx version: 2.1.1
# Python version: 3.5.2 (CPython)
# Docutils version: 0.15 release
# Jinja2 version: 2.10.1
# Last messages:
#   preparing documents...
#   
#   done
#   
#   writing output... [100%] index
#   
#   
#   
#   publishing documents... [100%] index
#   
# Loaded extensions:
#   sphinxcontrib.autohttp.flask (unknown version) from venv/lib/python3.5/site-packages/sphinxcontrib/autohttp/flask.py
#   sphinx.ext.coverage (2.1.1) from venv/lib/python3.5/site-packages/sphinx/ext/coverage.py
#   sphinxcontrib.autohttp.flaskqref (unknown version) from venv/lib/python3.5/site-packages/sphinxcontrib/autohttp/flaskqref.py
#   sphinxcontrib.htmlhelp (1.0.2) from venv/lib/python3.5/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.3) from venv/lib/python3.5/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   alabaster (0.7.12) from venv/lib/python3.5/site-packages/alabaster/__init__.py
#   sphinxcontrib.devhelp (1.0.1) from venv/lib/python3.5/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.applehelp (1.0.1) from venv/lib/python3.5/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinx.ext.intersphinx (2.1.1) from venv/lib/python3.5/site-packages/sphinx/ext/intersphinx.py
#   sphinxcontrib.qthelp (1.0.2) from venv/lib/python3.5/site-packages/sphinxcontrib/qthelp/__init__.py
#   sphinxcontrib.httpdomain (unknown version) from venv/lib/python3.5/site-packages/sphinxcontrib/httpdomain.py
#   sphinxcontrib.confluencebuilder (1.1.0) from venv/lib/python3.5/site-packages/sphinxcontrib/confluencebuilder/__init__.py
#   sphinx.ext.doctest (2.1.1) from venv/lib/python3.5/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.autodoc (2.1.1) from venv/lib/python3.5/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.mathjax (2.1.1) from venv/lib/python3.5/site-packages/sphinx/ext/mathjax.py
Traceback (most recent call last):
  File "venv/lib/python3.5/site-packages/sphinx/cmd/build.py", line 284, in build_main
    app.build(args.force_all, filenames)
  File "venv/lib/python3.5/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_all()
  File "venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 278, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "venv/lib/python3.5/site-packages/sphinx/builders/__init__.py", line 385, in build
    self.finish()
  File "venv/lib/python3.5/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 465, in finish
    self.publish_doc(docname, output)
  File "venv/lib/python3.5/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 346, in publish_doc
    uploaded_id = self.publisher.storePage(title, output, parent_id)
  File "venv/lib/python3.5/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 540, in storePage
    uploaded_page_id = rsp['id']
KeyError: 'id'

```

**Comment by jdknight** [comment]
@chinmayprabhudesai, I do not see anything that would prevent this extension working with the `sphinxcontrib.httpdomain` extension. Using the [examples](https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/) from httpdomain's documentation can result in an output on Confluence:

![image](https://user-images.githubusercontent.com/1834509/63659582-26128500-c780-11e9-8c0b-70402459ebc1.png)

The error reported in the example logs:

```
...
    uploaded_page_id = rsp['id']
KeyError: 'id'
```

Indicates that the issue is not generating the documentation, but there is an issue with attempting to complete a publish request. For some reason, the `POST` request to Confluence succeeds (without exception or the extension is not properly handling the error) but the response does not provide an identifier (`id`) in the results.

Is this issue repeatable? I am curious to know if this happens for all of your documents (i.e. this extension is not handling the content correctly on a specific document) or if all of your publish events are failing (i.e. this extension is not gracefully handling authentication/requests/some-Confluence-extension/etc.).

**Comment by jdknight** [comment]
@chinmayprabhudesai, I do not believe this would have to do with any changes related to GDPR in Confluence. I would believe it would be more of an issue with respect to a proxy or SSO solution for your target instance (speculation).

While I cannot give an specific answer to resolve this issue, changes from #260 have been just merged into `master` which should provide a dump of JSON data (if any; in an API error message) in the event where a new-page request provides a response without an identifier. If you are still observing this issue, this change might reveal more to help determine the cause.

**Comment by chinmayprabhudesai** [comment]
@jdknight , Thanks for getting back to this ticket, I'll retry to publish my docs

**Comment by rite2hhh** [comment]
@jdknight,

Apologies for getting back with such a big gap, but that's how long it took for me to resume to my project.

It worked!!! I successfully published my HTTP API to Confluence <3


```
$ sphinx-build --version
sphinx-build 3.0.1
$ pip3 list | grep sphinx
...
sphinxcontrib-confluencebuilder 1.2.0                 
sphinxcontrib-httpdomain        1.7.0                 
...
```
