### ISSUE TITLE
NotImplementedError: unknown node: admonition

### ISSUE THREAD

**Issue by amberlin** [sphinx-contrib/confluencebuilder#226]
I am trying to render documents that contain traces from the `mlx.traceability` extension.  Those documents crash when the admonition directive is reached.  Is there anything I can do to have these documents render?

Versions:
sphinxcontrib-confluencebuilder's extension version - `sphinxcontrib-confluencebuilder-1.2.0.dev0`
Python version - `Python 2.7.15`
Sphinx verison - `Running Sphinx v1.6.3`

Crash message:
```
Exception occurred:
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinxcontrib/confluencebuilder/translator.py", line 136, in unknown_visit
    raise NotImplementedError('unknown node: ' + node.__class__.__name__)
NotImplementedError: unknown node: admonition
```

Full Log - [sphinx-err-e1wEh0.log](https://github.com/sphinx-contrib/confluencebuilder/files/3527234/sphinx-err-e1wEh0.log)

**Comment by jdknight** [comment]
@amberlin, thanks for the information. This issue should now be resolved in `master` (see #227) and will be available via PyPI on next stable release.
