### ISSUE TITLE
handle new confluence cloud style (august 2019)

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#229]
Atlassian has rolled out [Confluence's new look](https://confluence.atlassian.com/confcloud/new-navigation-and-a-new-look-for-confluence-881536766.html) which breaks numerous features of this extension. 😑

Various examples include block level changes:

![image](https://user-images.githubusercontent.com/1834509/63825346-7a586900-c928-11e9-90b3-06c7c3d90c81.png)

Image issues:

![image](https://user-images.githubusercontent.com/1834509/63825351-7fb5b380-c928-11e9-9d88-ef4490fdbed6.png)

File thumbnail issues:

![image](https://user-images.githubusercontent.com/1834509/63825361-88a68500-c928-11e9-8830-fab55cd46adf.png)

Missing nested table support:

![image](https://user-images.githubusercontent.com/1834509/63825370-91975680-c928-11e9-9248-72c32d092fed.png)

---------

Every feature will need to be re-checked for compatibility. There may need to be a modification to target what type of Confluence style type (possibly `stock` and `legacy` targets; assuming content cannot be restyled to handle both environments). It may be time to try to introduce a request to `/rest/applinks/1.0/manifest` to see what version the target Confluence instance is running on. Unfortunately, this slightly break process as there would need to be a REST request before we begin to translate any documents.

**Comment by liorella** [comment]
hi, I'm using the builder and up until yesterday everything worked really well and I was very happy.

Could you give a general idea for the timeline for resolving this issue?

**Comment by jdknight** [comment]
@liorella, it is hard to say at the moment (maybe over a month). Tried looking at multiple issues today and there are a series of features that are no longer supported (from what I can tell). From an initial pass of features checks (testing on Confluence Cloud v1000.0.0-cf9c3d59a55), new limitations includes:

- Format styles such as bullet lists can no longer be properly indexed in a paragraph (Confluence now ignores (select) style hints on div elements).
- Images can no longer be on the same line.
- Images can no longer be link-wrapped.
- Nested tables are no longer possible.
- Panels appear to no longer be supported, causing issues for figure containment (attempts to replace with tables fail since images inside cells can no longer be aligned).
- Table format changes no longer graceful present bibliographic fields.
- Line numbers in code blocks can no longer be removed.
- Attachment macro no longer gracefully displays attachment previews; and the base blank attachment type no longer displays a label matching the filename (although somehow works via editor; even though the storage format is the same).
- Only a single attachment entity can exist on a single line now.

Still will try to investigate ways around these issues. It may be that these limitations are here to say and this extension will be tweaked to warn about incompatibilities (when possible).

**Comment by liorella** [comment]
that sounds pretty awful, if it's really here to stay, it's a really terrible move from atlassian.
Let's hope things improve!

**Comment by jdknight** [comment]
Testing out various changes to handle future Confluence changes, some things will be manageable and some will not. In wondering the best way to approach translator changes to handle Confluence's redesign, I am currently leaning towards introducing a temporary configuration entry which when introduced, will publish documents in the "new style". This will allow existing users to continue as is with their Confluence server installations with no changes. Confluence Cloud users and (I suspect) Confluence 7+ beta users will need to set an interim configuration option. As time moves on (or if something else is suggested ahead of time), we can try to find a better way to deal with these two design styles.

To discuss actual changes to the translator to support Confluence's new design style... the first issue, which (IMHO) is the biggest "blocker", is finding a way to properly indent content for published documents. At this time, I have yet to find a solution. [CONFCLOUD-65755](https://jira.atlassian.com/browse/CONFCLOUD-65755) does mention changes to deal with idented action items which could expose capabilities to allow us to indent content again, but this is an assumption. I made [a request](https://community.developer.atlassian.com/t/how-to-indent-content-with-new-page-format-2019/32401) in Atlassian's developer community to see if anyone else knows of a solution -- maybe this may spawn something. I doubt we will ever see support for nested tables again (UI support was removed in 2017, and in 2019 it appears the new storage format parse no longer accepts it; see also [CONFCLOUD-58656](https://jira.atlassian.com/browse/CONFCLOUD-58656)).

I am partially hesitant to manage any new changes at this time until we find a proper solution for this indentation limitation. While it is unfortunate that some of this pull requests are being put on hold, I would rather not have to commit a large amount of time to support the new series of changes to only find out that Confluence's new builds just do not like to play nicely with external generators (although, maybe I am too fixed on the idea that paragraph formatting is more important than it is).

**Comment by liorella** [comment]
this makes a lot of sense, unless atlassian decides on a long term support
for these features, it's a bad idea to spend a lot of time to adapt to them.

Thanks!

**Comment by jdknight** [comment]
Performing a validation test on the most recent Confluence Cloud and Confluence Server 7.1 beta shows that various capabilities have been restored. One minor tweak has been queued up (#238) to deal with at least one observed issue. It is unknown at this time what is going to happen, but will assume for the best based on recent observations. An oddity observed with validation results do show that some pages will render new admonitions styles while some render older admonitions styles -- so who knows if new issues may arise in the future.

Will be trying to ramp-up work to address some pull requests soon. In the event that during this work it appears new style changes do not appear to be a major issue anymore, this issue will most likely be closed. If new concerns related to styling issues arise, they will be addressed here.

**Comment by jdknight** [comment]
While performing release testing for the v1.2 release, there did not appear to be any major issues for Confluence Cloud (and server variants). There is still a suspicion that the new Confluence page type will become the "default" page type in the future, which will most likely require some changes.

Since this is not an immediate concern, closing this issue for now.
