### ISSUE TITLE
confluence_max_doc_depth and KeyError: 'citations'

### ISSUE THREAD

**Issue by never147** [sphinx-contrib/confluencebuilder#232]
I am new to using confluence builder and attempting to squash the pages into a single page with confluence_max_doc_depth = 0. When I set the option to anything under the depth created (e.g. <4) I get the following error:

```
preparing documents... failed

Exception occurred:
  File "/home/matthbak/Apps/virtualenvs/oci_cva_updater/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 529, in _fix_std_labels
    for key, (fn, _l, lineno) in list(domain.data['citations'].items()):
KeyError: 'citations'
```

Sphinx version: 2.2.0
Python version: 3.6.8 (CPython)
Docutils version: 0.15.2 release
Jinja2 version: 2.10.1
[sphinx-err-o58iwlw1.log](https://github.com/sphinx-contrib/confluencebuilder/files/3606290/sphinx-err-o58iwlw1.log)

**Comment by jdknight** [comment]
@never147, changes introduced in Sphinx v2.1+ has resulted in modifications required to dealing with citations. This issue has been addressed in 59388455bd3de8c99d7be5c5307f3792d30cc9d6 and will be made available in next release of this extension (v1.3+). For now, you can opt for using the [`master`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/install.html#master) branch or you can attempt to downgrade your version of Sphinx to an older v1.8 version.
