### ISSUE TITLE
Ignore unknown nodes

### ISSUE THREAD

**Issue by vancheese** [sphinx-contrib/confluencebuilder#236]
Is it possible for confluence builder to be configured to ignore unknown nodes and corresponding sections instead of crashing out. with a NotImplementedError?
I know that this wouldn't be ideal for everyone but could there be a variable which contains a list of nodes to ignore e.g.,

ignore_node = ["this"]

I'm currently crashing out with a mermaid node (a feature not 100% critical for my confluence export)

**Comment by jdknight** [comment]
#248

**Comment by jdknight** [comment]
This feature is now available on `master` through an advanced (undocumented) `confluence_adv_ignore_nodes` configuration option. This feature should also be made available next stable release.
