### ISSUE TITLE
travis-ci migration needed

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#243]
Appears with some maintenance work, travis-ci.org has been deauthorized from the project and no longer permits re-adding projects (at least, for the sphinx-contrib group) back. There is an option to migrate the project to travis-ci.com (which is fine); however, it appears only owners of the project may authorized this action:

> ![image](https://user-images.githubusercontent.com/1834509/67736746-152ffb00-f9df-11e9-9d04-bd72f47dcc46.png)

@stephenfin, can I get an assist? (also, if there is a proper channel to do these requests, I do not mind going that route for this and possibly other requests)

**Comment by stephenfin** [comment]
I think this has been resolved now by enabling Travis CI for the organization. Please let me know if I've missed something.

**Comment by jdknight** [comment]
Interesting, I was under the assumption that only travis-ci.com projects could be created now instead of travis-ci.org projects. In any case, I am just happy CI tasks working again.

**Comment by jdknight** [comment]
@stephenfin, I just noticed that am I unable to interact with privileged actions on the Travis CI (org)-based project. For example, if I try to manually re-start a failed build, the option does not appear to be available:

![image](https://user-images.githubusercontent.com/1834509/69897723-c0eda300-131d-11ea-8aaf-4cb2030a4510.png)

I noticed when I browse under sphinx-contrib's Travis CI (com)-based projects, I have the ability to trigger a job (although, I am not sure if it is expected that I have the ability to trigger other project's jobs):

![image](https://user-images.githubusercontent.com/1834509/69897754-30639280-131e-11ea-9705-b505c48da934.png)

If you are willing, can you see if there is a way to authorize maintainers for this project to trigger rebuilds on the project; or maybe try to [trigger the migration to Travis-ci.com](https://travis-ci.com/sphinx-contrib/confluencebuilder) which may resolve this issue as well?

**Comment by stephenfin** [comment]
I've triggered the migration. Can you let me know if that works for you?

**Comment by jdknight** [comment]
@stephenfin. I believe it is working now. Just did a simple test by restarting a single job. Thanks for the help; much appreciated.
