### ISSUE TITLE
Numbered page titles and section headers

### ISSUE THREAD

**Issue by jessetan** [sphinx-contrib/confluencebuilder#256]
This is a poll for interest in the ability to add section numbering to sections and page titles.
I have a rough implementation, but I would like to know if this is within the spirit of this extension before I invest more time.

The use of section numbers is not as applicable to web-based output as Confluence or HTML as it is to printed documents, but it can serve a purpose to indicate a suggested or required reading order.
The main driver for this feature is to add a section number before page titles so that they appear in the Confluence page tree in the correct order. Without this, Confluence will use alphabetical sorting order. Confluence does not support a way to reorder pages using the REST API (#4).
Something similar was started in #164, but this never made it into master.

Possibly related to #195

**Comment by jessetan** [comment]
Ping @jdknight, do you think this would be a suitable addition to this extension?

**Comment by jdknight** [comment]
@jessetan, I think such a feature could be beneficial for some users.

My only comment would be that I would assume such a feature would take into consideration [toctree's `:numbered:`](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-toctree) option and [`sectnum`](http://docutils.sourceforge.net/docs/ref/rst/directives.html#automatic-section-numbering). There is also [`html_secnumber_suffix`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_secnumber_suffix) which is related as well.
