### ISSUE TITLE
Use raw_input when asking for credentials on python 2.7

### ISSUE THREAD

**Issue by filmkorn** [sphinx-contrib/confluencebuilder#276]
First of all, I'm sorry to open a python 2.7 compatibility issue in 2020.

I'm using  `confluence_ask_password` and `confluence_ask_user` to ask for user credentials.

`input()` is evaluating the input as python code, I think raw_input should be used here?

sphinxcontrib-confluencebuilder: 1.2.0
Python version: 2.7.13
Sphinx version: 1.8.5

Best,

Mitja

**Comment by jdknight** [comment]
Thanks for reporting this issue. This should now be resolved on `master` via #285; and will be made available on PyPI next stable release (v1.3+).
