### ISSUE TITLE
maintenance: readthedocs access

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#292]
@tonybaloney, if possible, any chance [I](https://readthedocs.org/profiles/jdknight/) get can maintainer access on the ReadTheDocs's [sphinxcontrib-confluencebuilder project](https://readthedocs.org/projects/sphinxcontrib-confluencebuilder/)?

Hoping to have the ability to synchronize the stable tag when a release is made. I recall having access before, but I assume access was changed when this project was moved into sphinx-contrib (although I could be wrong).

**Comment by tonybaloney** [comment]
@jdknight what is your RTD username?

**Comment by jdknight** [comment]
@tonybaloney, it will be [`jdknight`](https://readthedocs.org/profiles/jdknight/).

**Comment by tonybaloney** [comment]
done. sorry it took me ages
