### ISSUE TITLE
RFC: new implementation header

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#302]
@tonybaloney, I am pondering on updating the default header format for this extension. An existing example (pulled from [`translator.py`](https://github.com/sphinx-contrib/confluencebuilder/blob/6af64c6244bba60d540d9290d08300a5460eb135/sphinxcontrib/confluencebuilder/translator.py#L1-L6)) is the following:

```
# -*- coding: utf-8 -*-
"""
    :copyright: Copyright 2016-2019 by the contributors (see AUTHORS file).
    :copyright: Copyright 2018 by the Sphinx team (sphinx-doc/sphinx#AUTHORS)
    :license: BSD-2-Clause, see LICENSE for details.
"""
```

I am hoping to possibly change it to the following (for the above example):

```
# -*- coding: utf-8 -*-
# Copyright 2016-2019 Confluence Builder for Sphinx Contributors (see AUTHORS).
# Copyright 2018 by the Sphinx team (sphinx-doc/sphinx#AUTHORS)
# Licensed under BSD-2-Clause (see LICENSE).
```

Any objections/comments?

**Comment by tonybaloney** [comment]
I prefer the file/module level docstrings. 

Why are you considering using single-line comments instead? They no longer become an attribute of the file that you can programmatically discover (if you chose to)

**Comment by jdknight** [comment]
> I prefer the file/module level docstrings.

If the docstring style is preferred, that is fine with me.

The primary intention for the prospect header was to first adjust the ambiguous "by the contributors" phrasing to something more explicit towards this extension (while also trying to stay within an 80-character limit).

> Why are you considering using single-line comments instead? They no longer become an attribute of the file that you can programmatically discover (if you chose to)

I never found the inclusion of copyright or license information useful in any sort of documentation-related comment (whether it be Python, C, etc.). For the use cases where I have seen file-level documentation extracted from a source file and the cases where copyright/license information is "forced" on a given document, this extra content always struck me as an annoyance and wasteful of space. I have grown fond over these years to use single-line comments (if the language permits it) since they are simple to maintain (subjective).

That being said, I am only viewing this from a narrow scope. I cannot say I have seen tools which attempt to process these meta values for some purpose or use an IDE which may nicely reflect this information to a developer. If there is value leaving them there, I have no objection to continuing with that style.

---

To address one of my initial desires, how about something like the following:

```
# -*- coding: utf-8 -*-
"""
:copyright: Copyright 2016-2019 Sphinx Confluence Builder Contributors (AUTHORS)
:copyright: Copyright 2018 by the Sphinx team (sphinx-doc/sphinx#AUTHORS)
:license: BSD-2-Clause (LICENSE)
"""
```

Although, if there is a desire to have the leading spaces (possibly for a block quote or some type of indentation), it could be left the same formatting and the following can be done (choosing a more proper copyright statement over a lower-priority desire to limit the characters in a line):

```
# -*- coding: utf-8 -*-
"""
    :copyright: Copyright 2016-2019 Confluence Builder for Sphinx Contributors (see AUTHORS file).
    :copyright: Copyright 2018 by the Sphinx team (sphinx-doc/sphinx#AUTHORS)
    :license: BSD-2-Clause (see LICENSE file).
"""
```

**Comment by tonybaloney** [comment]
```
# -*- coding: utf-8 -*-
"""
:copyright: Copyright 2016-2019 Sphinx Confluence Builder Contributors (AUTHORS)
:copyright: Copyright 2018 by the Sphinx team (sphinx-doc/sphinx#AUTHORS)
:license: BSD-2-Clause (LICENSE)
"""
```
👍
