### ISSUE TITLE
Failure with automatic generated images, eg. blockdiag, seqdiag, actdiag

### ISSUE THREAD

**Issue by MarkusPoh** [sphinx-contrib/confluencebuilder#315]
While running the build the resulting png-files are stored in build/confluence  and **not** in the src-directory. 
So *ConfluenceUtil.hashAsset* fails.

The reason is *ConfluenceManager._interpretAssetPath* assumes that all images are located in the source-directory (assets.py: 261ff), which is wrong for generated images.

adding 
```
 if not os.path.isfile(abspath):
                targetdir = self.env.srcdir.replace("source","build/confluence")    
                abspath=os.path.join(targetdir,path)
```
will fix this for me.

**Comment by jdknight** [comment]
Interesting -- I cannot say I have tried these extensions myself, but I will try them out. I would agree that the current implementation of `_interpretAssetPath` will incorrectly assume that the path of any image/download-reference found would be part of the `self.env.srcdir` path (to generate an "absolute path").

A quick glace at the implementation, I would suspect that the path could already point to an absolute path for these cases and prefixing with `self.env.srcdir` could be skipped. If this is not the case, there should be a way to determine how the `sphinxcontrib-blockdiag` extension (and related extensions) decides where to store their generated assets.

**Comment by RiccardoManfrin** [comment]
I'm having the exact same issue
![image](https://user-images.githubusercontent.com/3090891/81565769-30ba8c00-939a-11ea-9c7b-24677aa3b2c1.png)
Can't instruct the plugin to lookup images in `./build/confluence` and not in `./`

**Comment by RiccardoManfrin** [comment]
Thanks for the proposed fix @MarkusPoh
In my case (possibly because I don't use abspaths) I had to work it around with

```
if not os.path.isfile(abspath):
            abspath=os.path.join('build/confluence/',path)
```
before the last return in `assets.py` around line 149. Dirty and effective

**Comment by jdknight** [comment]
@MarkusPoh and @RiccardoManfrin, thanks for the feedback. I was able to test against the `sphinxcontrib-blockdiag` which changes introduced in #326 (similar to the workaround mentioned in these comments). I believe this may resolve any case where an extension generates an asset into the build output directory and defines a relative path for a node. If you have any comments on the matter, feel free to comment. If all is good, this should be made available in the next stable release.

**Comment by jdknight** [comment]
In preparation for an upcoming release, this issue was rechecked with the changed outlined in #326. It appears all blockdiag project's diagram types (when a user loads the respective Sphinx extension), should work as expected. A quick test using the project example diagrams:

```
.. blockdiag::

   diagram {
     A -> B -> C;
          B -> D;
   }

.. seqdiag::

   seqdiag {
     browser => webserver => database;
   }

.. actdiag::

   actdiag {
     A -> B -> C -> D;

     lane {
       A; B;
     }
     lane {
       C; D;
     }
   }

.. nwdiag::

    nwdiag {
      network dmz {
          address = "210.x.x.x/24"

          web01 [address = "210.x.x.1"];
          web02 [address = "210.x.x.2"];
      }
      network internal {
          address = "172.x.x.x/24";

          web01 [address = "172.x.x.1"];
          web02 [address = "172.x.x.2"];
          db01;
          db02;
      }
    }
```

Will be published onto a Confluence instance:

![image](https://user-images.githubusercontent.com/1834509/100529432-b88caa00-31b5-11eb-9a6d-b1a4e9e9cc53.png)

Since this extension appears to work with the most recent developer revision of this extension, I will be marking this as pending-next-release and will close up once the upcoming release (v1.3; #362) is completed. Please feel free to make a comment on this issue if a concern still exists.

**Comment by jdknight** [comment]
v1.3 is now available on PyPI -- marking as closed.
