### ISSUE TITLE
publishing fails for multiple documents referencing same image

### ISSUE THREAD

**Issue by g-simmons2** [sphinx-contrib/confluencebuilder#317]
Hi, I am attempting to publish sphinx documentation to confluence, and encountering this error for pages with images. Pages without images publish with no problems up to the first page with an image, then the following error is thrown and publishing stops. The `"authorized": false` makes me think this could be a permissions error? Any help greatly appreciated.

```
Params
------
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] validation/validation                                                                                  
publishing documents... [  7%] overview/overview                                                                                
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 500
URL: https://company.atlassian.net/wiki/rest/api
API: content
DATA: {
  "statusCode": 500,
  "data": {
    "authorized": false,
    "valid": true,
    "errors": [],
    "successful": false
  },
  "message": "com.atlassian.confluence.api.service.exceptions.InternalServerException: java.lang.RuntimeException: com.atlassian.confluence.content.render.xhtml.storage.link.StorageLinkUnmarshalXhtmlException: java.lang.UnsupportedOperationException"
}
---
```

**Comment by g-simmons2** [comment]
Found out this only occurs if multiple rst files are referencing images of the same filename, so solved by copying and changing the filename of images that I would like to include in multiple locations.

**Comment by jdknight** [comment]
@g-simmons2, thanks for the report; will try to find a correction.

**Comment by ottowayi** [comment]
For me, just changing the file name did not work.  I had a bunch of SVGs that were reused (like button icons).  I made a unique copy for each place one was used, then opened them in a text editor and added some extra whitespace in a different spot for each image.  They still render the same, but I think making them hash uniquely solved the problem.

**Comment by g-simmons2** [comment]
@ottowayi iirc I noticed something similar in certain cases, where changing the filename didn't solve the problem and I had to change the file contents. I also recall looking into the `confluence_asset_override` configuration option, can't remember whether it was successful or not. 

https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-asset-override

**Comment by ottowayi** [comment]
@g-simmons2 I tried setting `confluence_asset_override = True` and it didn't help.  I only got it to work once I made sure the file contents were unique, not just the file names.

**Comment by jdknight** [comment]
Found it.

It appears to be an issue with how Confluence parses the elements inside an `ac:image` tag. When assets are shared between multiple pages, only a single asset is published (into the root document). This requires the attachment markup to point to the page which holds the attachment. The original implementation would be structured as follows:

```
<ac:image>
<ri:attachment ri:filename="confluence.png"><ri:page ri:content-title="ztest" />
</ri:attachment>
</ac:image>
```

However, this now results in a 500 error. By removing the newline found inside `ri:attachment`, the publish event will succeed:

```
<ac:image>
<ri:attachment ri:filename="confluence.png"><ri:page ri:content-title="ztest" /></ri:attachment>
</ac:image>
```

I will adjust all the markup building attachments to no longer inject a newline character (which will require updating a series of test logic as well).

**Comment by ottowayi** [comment]
@jdknight glad you found it, that's a really weird issue

**Comment by jdknight** [comment]
v1.3 is now available on PyPI -- marking as closed.
