### ISSUE TITLE
feature request: do not overwrite existing pages

### ISSUE THREAD

**Issue by extremoburo** [sphinx-contrib/confluencebuilder#321]
Hello, 

I can't find an option which check if a page in a confluence space already exists and avoids an unwanted overwrite ( maybe it could skip with a warning message ) . At the moment a publish will just overwrite anything even if was manually written. 

Thanks

**Comment by jdknight** [comment]
Was able to take a look at this in #327. Do you believe this cover what you are looking for?

**Comment by jdknight** [comment]
With the recent merge of #327 into `master`, the configuration option [`confluence_publish_onlynew`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-publish-onlynew) should provide a capability to prevent overwriting existing pages on publication. This feature should also be made available next stable release.
