### ISSUE TITLE
Can't Update Confluence Page

### ISSUE THREAD

**Issue by RajatDoshi** [sphinx-contrib/confluencebuilder#322]
Hey! 

I am developing a script to update content on a confluence wiki page using a REST API. I am successfully able to send a GET request to a certain endpoint but when I send a PUT request to that same page, I am getting a 400 error. I printed the logs and found that the specific error is: "errors":[{"message":{"key":"You can\'t change an existing page\'s space.","args":[]}}]. Any advice on how to properly debugging this would be greatly appreciated. Thanks in advance for any help! Please find below my code.

`
url = 'https://[company].atlassian.net/wiki/rest/api/content/774636582'

authInfo = ('email', 'API KEY')

headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
}

data = '{ "id":"774636582", "type":"page", "title":"TestPage", "space":{"key":"PS"}, "body":{ "storage":{ "value":"<p>This is the updated text for the new page</p>", "representation":"storage" } }, "version":{ "number":4} }'

response = requests.put(url, headers=headers, data=data, auth=authInfo)
`

**Comment by jdknight** [comment]
Note that this issue system is mainly for issues when interacting with a Confluence instance using the Sphinx Confluence Builder extension. It would be recommended to consult [Atlassian's developer community](https://community.developer.atlassian.com/) for help in these cases.

That being said, it is most likely either one of the following issues from the information provided:
- You are attempting to move a page identified with the value `774636582` from a space that was not named `PS` to a space named `PS`. It is unsupported using Atlassian REST API (to my knowledge) to change pages between spaces.
- The space key value is case-sensitive. The above example is using a space key `PS`; however, if you are attempting to update a page on a space named `ps`, this will not work (see also [CONFSERVER-40303](https://jira.atlassian.com/browse/CONFSERVER-40303)).

**Comment by RajatDoshi** [comment]
The error was indeed in the space key - thank you so much @jdknight!
