### ISSUE TITLE
Sphinx Page Contents not working

### ISSUE THREAD

**Issue by shivav** [sphinx-contrib/confluencebuilder#323]
Hello,

Thanks for providing this package. During build, it's publishing the contents but the sub section Heading links are not working.

The following is the rst snippet which expands page headings and creates contents links at the top of the page.

The links are showing up but when clicked are not taking user to the heading section.

.. contents::
    :depth: 2

Thanks in advance.
Shiva

**Comment by jdknight** [comment]
@shivav, indeed there is an issue when attempting to use reStructuredText's [`contents`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents) directive. Typically, most users have been using Sphinx's [`toctree`](https://www.sphinx-doc.org/en/1.8/usage/restructuredtext/directives.html#directive-toctree) instead; however this extension should be attempting to support both types of table-of-contents capabilities.

Will try to find a solution.

Note that the `contents` directive should work at this time with the `local` option (if the desire is only for local page headings only):

```
.. contents::
   :local:
```

**Comment by shivav** [comment]
Hello James,

Thanks a lot for your email. It means a lot that you guys have given us
this awesome package.

I tried the following but it didn't work. like the subheading links are
showing up but the links are dead links. it doesn't take the user to the
section.

.. contents::
   :local:

We want a section on confluence with links to different headings. I am
not sure how toctree can be used for this purpose.


Regards

Shiva

**Comment by jdknight** [comment]
@shivav, I am curious to know more about your use case.

I took some time today and was not able to explicitly observe cases where a reStructuredText's contents directive produced references which did not generate a link. My previous comment above does indicate that there was a bug, but this was a result of a quick observation where a visual error was observed (without additional checks):

> ![image](https://user-images.githubusercontent.com/1834509/100433486-29727b80-3069-11eb-90d4-bb80ae6259ff.png)

For the visual issue, a solution has been found and prepared in #360. During the development/testing of this change, there was never an observation of a link not properly building.

During the validation testing for this extension, there are at least two cases where we use the `contents` directive. First in the ["lists" sample](https://jdknight.atlassian.net/wiki/spaces/confluencebuilder/pages/905773117/v1.2-lists) [[src]](https://github.com/sphinx-contrib/confluencebuilder/blame/master/tests/validation-sets/common/lists.rst#L7-L9), second in the ["other" sample](https://jdknight.atlassian.net/wiki/spaces/confluencebuilder/pages/904070405/v1.2-other) [[src]](https://github.com/sphinx-contrib/confluencebuilder/blame/master/tests/validation-sets/common/other.rst#L7-L8). In both cases (which were produced using, at the time, the current stable release), the links are generating proper links. One assumption could be that you may been in a situation where all sections you wanted to jump were visual on the rendered page, where the target link will not visually jump in most browsers (most likely can be observed in the second example mentioned above).

That all being said, I want to make sure I am not missing the specific issue. If you have additional information (addition configuration options, raw output data, etc.) or a more detailed example, it would be most welcome.

**Comment by jdknight** [comment]
When examining #346 which outlines broken TOC links with section numbers, it exhibits the same issues outlined here. Since #346 is a bit more explicit with what feature is causing the issue and the contents display issue has been resolved in #360, I am going to go ahead and close this issue.

Further discussion on this will be continued in #346. @shivav, thanks for the initial report -- will try to resolve this issue soon.
