### ISSUE TITLE
jira_issue directive with html builder

### ISSUE THREAD

**Issue by Cielquan** [sphinx-contrib/confluencebuilder#337]
Platform: Windows 10 Enterprise 64bit 1909
Python: 3.8.2
Sphinx: 3.1.2
confluencebuilder: 1.2.0 and 1.3.0-dev0
Project: https://github.com/Cielquan/python_test

When I add a `jira_issue` directive into the docs e.g. index.rst and build it with the confluence builder it works with 1.2, but not so really on 1.3-dev0 (but thats another topic). When I want to build the docs with the html builder I get the error below, because the `jira_issue` directive is missing, which I don't understand because the config.py does not change and the confluencebuilder extension is included.

```console
Exception occurred:
  File "c:\users\riedelc\projects\python_test\.tox\docs\lib\site-packages\sphinx\writers\html5.py", line 790, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: jira_issue
The full traceback has been saved in C:\Users\xxx\AppData\Local\Temp\sphinx-err-elo188s7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ERROR: InvocationError for command 'C:\Users\xxx\Projects\python_test\.tox\docs\Scripts\sphinx-build.EXE' -b html -aE docs/source docs/build/html (exited with code 2)
```

When I add a `setup` func to the config like this (and add `-t builder_confluence` to the command):

```python
def setup(app):
    if not tags.has("builder_confluence"):  # type: ignore # noqa
        from sphinx.directives import SeeAlso
        app.add_directive("jira_issue", SeeAlso)
```

I get the Warning:

```console
WARNING: while setting up extension conf.py: directive 'jira_issue' is already registered, it will be overridden
```

Which is even stranger.

**Comment by jdknight** [comment]
The directive implementations introduced by this extension are specifically designed for this extension. If the content being generated uses the directives provided in this extension but also want to handle other builder types, there are ways to get this to work. The current solution available is to use the [`only` directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-only), which would allow you to exclude the custom directives from this extension. For example:

```
.. only:: confluence and singleconfluence

    .. jira_issue:: TEST-123
```

Although, I can agree this does not look pretty and a bit annoying if you want to build against the standard builders (html, latex and text). This extension should see if there is a way to gracefully handle standard builders to suppress the content in these nodes.

Note that the directives introduced are not really designed to support the standard builder types (let alone any other builder types -- would be out of the scope for this extension). There is flexibility for other extensions to override the node implementations (if desired) -- this extension [only registers the internal nodes if they are not already registered](https://github.com/sphinx-contrib/confluencebuilder/blob/v1.2/sphinxcontrib/confluencebuilder/__init__.py#L193-L196) (for advanced cases/external extensions to work with).

Another workaround, if you want to avoid editing the content itself, would be to suppress or manipulate the node content yourself (in a manner similar to what you mentioned above). For example, to ignore the `jira_issue` directives in the `html` builder, a user could do the following in their configuration:

```
from docutils import nodes
from sphinxcontrib.confluencebuilder.nodes import jira_issue

def setup(app):
    def visit_ignore(self, node):
        raise nodes.SkipNode
    app.add_node(jira_issue,
        html=(visit_ignore, None))
```

One can even be more bold an try to create content based off the node itself, but note that the node implementations are subject to change (e.g. there will be some future changes to address an issue with the JIRA-based implementation and the `singleconfluence` builder; 860d6e82f412ea02a515cd4583a60db5b1dc95aa).

**Comment by Cielquan** [comment]
Thanks for the lengthy answer. 😄 

The only directive sound good as a basic workaround. But then there is no link to the jira issue.

What I would like to have is at least a note mentioning the jira issue, optionally with a link to the issue. Therefore my example with the seealso directive, which is deprecated in 4.0.
It has not to be like the implementation in the confluence docs, with issue status etc., but would be very nice. I don't know if it's possible or in which range it would be possible to implement.

I will take a deeper look in the node manipulation thing and post my solution here, when I find one satisfying my ideas.

**Comment by Cielquan** [comment]
Based on my initial proposal with the `seealso` directive I have found a solution.

It will add a "See also" info box when not using the confluence builder (or rather not setting `-t builder_confluence`) and have "JIRA issue: <link to issue>" as content.

You need to add the snippet below to your `conf.py`:
``` python
extensions.append("sphinx.ext.extlinks")
extlinks = {"jira_issue": ("<LINK TO YOUR JIRA INSTANCE>/%s", "")}

if tags.has("builder_confluence"):
    extensions.append("sphinxcontrib.confluencebuilder")

def setup(app):
    if not tags.has("builder_confluence"):
        from sphinx.directives.other import SeeAlso

        class _SeeAlso(SeeAlso):
            def run(self):
                self.content[0] = "JIRA issue: " + f":jira_issue:`{self.content[0]}`"
                return super().run()

        app.add_directive("jira_issue", _SeeAlso)
```

The solution works for plain `jira_issue` directives without any paramters like `.. jira_issue:: XXX-1`. If you want to use e.g. the `:server-id:` parameter you have to change the code to support that.
