### ISSUE TITLE
Aesthetic of the documents

### ISSUE THREAD

**Issue by JavierLopezT** [sphinx-contrib/confluencebuilder#342]
Hello! First of all, I would like to thanks all contributors to this project, the tool is very useful!!

I am creating documents with embedding code, and I think the result in confluence is less beautiful compared to the HTML or native confluence. For instance:
Html
![Captura de pantalla 2020-09-09 a las 16 21 17](https://user-images.githubusercontent.com/11339132/92610889-7e97c000-f2b8-11ea-9339-af58c55bca33.png)
Once exported to confluence
![Captura de pantalla 2020-09-09 a las 16 23 38](https://user-images.githubusercontent.com/11339132/92611188-d33b3b00-f2b8-11ea-8047-cfc313d986ca.png)

Is there any way of making the export in confluence more similar to the HTML? 

Thank you very much in advance

**Comment by jdknight** [comment]
> Is there any way of making the export in confluence more similar to the HTML?

@JavierLopezT, unfortunately not.

This extension provides the ability to translate output into a format compatible with Atlassian's Confluence; however, this extension has no control over the look-and-feel of the content being rendered (other than applying classes, if able, to select elements). For example, code from a reStructuredText/Sphinx-supported document will be wrapped in a Confluence's storage-format `code` tag -- styling is all managed by the theme configured on the given space. If you are looking for a better way to visualize code content for a given space, it would be recommended to look for an [alternative theme](https://confluence.atlassian.com/doc/working-with-themes-151522.html) for your space (if possible).

Depending on your use case, it may be better to stick to using the `html` builder and using a simple HTTP server to host your documentation. This extension mainly (IMHO) provides support for developers who are "stuck" sharing documentation through a Confluence instance, where project management and access controls can be managed for a group/project.

**Comment by jdknight** [comment]
As mentioned above, the aesthetics of a published documentation set is subject to the theme of the space (and not this extension). Marking as closed.
