### ISSUE TITLE
Open API support

### ISSUE THREAD

**Issue by Mikulasi** [sphinx-contrib/confluencebuilder#352]
Hi! Thanks for a great job man. Is it possible to attach this macro to the builder? -> https://marketplace.atlassian.com/apps/1215176/open-api-documentation-for-confluence?hosting=cloud&tab=overview

Thanks

**Comment by jdknight** [comment]
@Mikulasi, unfortunately, the "Open API Documentation for Confluence" application for Confluence is not really something that would directly be managed by this extension. Aside from its fact that access to the application is not free (which makes development/maintenance efforts an issue), this Confluence Builder extension is goaled to support restructuredText/Sphinx markup, provide some support (where possible) for official Atlassian-provided macros/features (e.g. JIRA markups) and provided access points for other extensions.

It is possible for a user/developer to build a custom extension which can interact with this extension to provide a custom directive to build an Open API macro(s). There exist a sample project [sphinx-confluence-nbsphinx-test](https://github.com/jdknight/sphinx-confluence-nbsphinx-test) which provides a partial example of what can be done through a third-party extension to help inject macro content into a generated document.

The only alternative that exists right now is manually injecting raw structured-macro content in a document. For example (based off a [comment](https://community.atlassian.com/t5/Marketplace-Apps-Integrations/How-to-define-the-open-api-marco-in-confluence-markdown/qaq-p/1113699#M61786) observed in the Atlassian community):

```
.. raw:: confluence

    <ac:structured-macro ac:name="open-api">
        <ac:parameter ac:name="url">TODO_URL</ac:parameter>
        <ac:plain-text-body><![CDATA[ TODO_CONTENT ]]></ac:plain-text-body>
    </ac:structured-macro>
```

However, there is no way to confirm that above macro will work as expected without having access to the application.
