### ISSUE TITLE
Support for "Expand Macro" (i.e. Collapsible Sections)

### ISSUE THREAD

**Issue by wfranceys** [sphinx-contrib/confluencebuilder#356]
Hi @jdknight, thank you for building and maintaining this package!

I wanted to check into whether it is possible to use the [Expand Macro](https://confluence.atlassian.com/doc/expand-macro-223222352.html) to add collapsible sections. I couldn't see anything in the existing supported [markup list](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/markup.html) but I may be missing a trick.

Thanks again,
Will

**Comment by jdknight** [comment]
@wfranceys, the only way to take advantage of the "Expand Macro" and any other Confluence-specific that is not identified under the [directives documentation](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/directives.html) is to inject raw storage-format implementation inside the documentation. For example:

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque fermentum commodo purus, quis commodo eros venenatis id. Ut in ante condimentum arcu sagittis tempus quis vel elit. Nunc pretium hendrerit varius. Vestibulum placerat tristique est, a bibendum odio egestas non. Suspendisse vehicula turpis vel pretium hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; In vehicula dolor sed lectus sodales, vel pulvinar leo tempor. Morbi ac aliquam lacus. Nam lectus lacus, efficitur quis hendrerit ac, eleifend sit amet massa. Donec ac orci vestibulum, vulputate dolor non, sollicitudin metus.

.. raw:: confluence

    <ac:structured-macro ac:name="expand">
      <ac:parameter ac:name="title">Expand me...</ac:parameter>
      <ac:rich-text-body>

Donec malesuada, est nec faucibus blandit, tellus justo tempor tortor, nec dignissim nulla turpis at odio. Suspendisse accumsan porta quam, sit amet egestas velit aliquam non. Sed ac varius turpis. Etiam mollis erat non justo blandit, congue interdum elit imperdiet. Phasellus eros risus, posuere sit amet urna ac, mollis vestibulum ante. Proin quam nulla, efficitur non justo sed, efficitur tincidunt ligula. Aliquam enim neque, ullamcorper nec egestas at, rhoncus eu elit. Nulla neque diam, tincidunt a nibh non, posuere auctor diam. Sed interdum, libero non lobortis blandit, libero metus sagittis ante, nec efficitur eros leo a arcu. Donec at lacinia tellus, in pretium sapien.

.. raw:: confluence

      </ac:rich-text-body>
    </ac:structured-macro>

Etiam maximus aliquam nulla, et faucibus nulla commodo id. Morbi congue sem et sem aliquet sagittis. Donec egestas mi vel sapien vehicula, eu molestie ex aliquet. Duis pulvinar dolor in nisl cursus porttitor. Nullam posuere fringilla lorem vitae aliquam. Suspendisse eget dui commodo neque accumsan maximus in quis ante. Praesent sagittis in massa eu sagittis. Proin id iaculis justo. In lobortis auctor massa, sed pharetra leo condimentum nec. Pellentesque id lorem nisl.
```

For now, I will mark this an an enhancement.

A related note is that the above uses a `confluence` identifier string, which is planned to be deprecated next release for a `confluence_storage` string (to prepare support for both ADF and storage formats). Just giving a warning if you do take advantage of the `raw` directive and wonder why it reports a deprecated warning in a future release.

**Comment by wfranceys** [comment]
@jdknight Thanks James!

**Comment by jdknight** [comment]
Was able to take some time to look at this before the v1.3 release. With the merge in of #402, a new expand directive `confluence_expand` is now included in the main branch and should be made available next release (just need to test on older Confluence revisions to make sure there is no issues). Documentation is currently being re-worked right now which will include more information.

**Comment by wfranceys** [comment]
@jdknight Amazing, thanks James!
