### ISSUE TITLE
Error when a .rst file contains only an empty section

### ISSUE THREAD

**Issue by adreyfus** [sphinx-contrib/confluencebuilder#410]
Hi,

Thank you for your excellent work.

I encountered a problem with the .rst files which only contain a section title, without content. 

For example :

index.rst :

```
.. _configuration_index:

Configuration
#############

```
The file index.conf is not generated, then the error  

`WARNING: error reading file C:\.../config/index.conf: [Errno 2] No such file or directory: 'C:\\.../config/index.conf'
` 

appears, and sections are missing in the result sent on Confluence.

To get around it, of course, you just have to put something in the section, like "to be completed". But I report this because I guess this is not voluntary behavior :) .

**Comment by jdknight** [comment]
Thanks for reporting this. This should now be supported on the main branch (via #411) and should be made available next stable release (v1.3).

**Comment by jdknight** [comment]
v1.3 is now available on PyPI -- marking as closed.
