### ISSUE TITLE
:numref: crashes generation of confluence pages

### ISSUE THREAD

**Issue by adaszek** [sphinx-contrib/confluencebuilder#422]
Hi,

I have a problem with generation of confluence pages:

`Exception occurred:
  File "/home/adaszyns/.local/lib/python3.7/site-packages/sphinxcontrib/confluencebuilder/translator.py", line 149, in unknown_visit
    raise NotImplementedError('unknown node: ' + node_name)
NotImplementedError: unknown node: number_reference
The full traceback has been saved in /tmp/sphinx-err-42l394h6.log, if you want to report the issue to the developers.
`

content of error: https://gist.github.com/adaszek/4c3f72d7781c34b3cf625891fa977cf5

I use :numref:`name` to refer to figures with :caption: name.

**Comment by jdknight** [comment]
Unfortunately support for `:numref:` was never added to this extension.

A local fix is available to support `:numref:` and hopefully `:math:numref:` to be merged in this weekend. Marking for a v1.4 release for now and hopefully this will be ready for use starting next week.

Thanks for reporting this issue.

**Comment by jdknight** [comment]
Support for `:numref:` should now be available on the main branch (via #427) and should be made available next stable release ([v1.4](https://github.com/sphinx-contrib/confluencebuilder/milestone/7)).

**Comment by jdknight** [comment]
v1.4 is now available on PyPI -- marking as closed.
