### ISSUE TITLE
confluence_ask_password=0 not working on 1.3

### ISSUE THREAD

**Issue by ExaneServerTeam** [sphinx-contrib/confluencebuilder#423]
Hello,

My documentation is generated though a Jenkins robot.

This command works in *1.2* but does not in *1.3*, thus killing all the automation. From my documentation reading it should still work.

Did I miss something ?

```
 make SPHINXOPTS="-D confluence_ask_password=0 -D confluence_server_pass=MY_PASSWORD" confluence
````

**Comment by ExaneServerTeam** [comment]
As the config param are no more initialized the SPHINXOPTS are interpreted as strings. The PR fixes the issue (Setting it back on what is was on 1.2)

**Comment by jdknight** [comment]
Apologies -- recent configuration changes did not take into account of the type hinting in the `add_config_value` call.

I will address this hopefully tomorrow or the next day; with the goal of having a v1.4 quick release this weekend available for next week.

If you have not yet locally patched a workaround for your environment, the following workaround may work for you (if it helps):

```
make SPHINXOPTS="-D confluence_ask_password= -D confluence_server_pass=MY_PASSWORD" confluence
```

**Comment by ExaneServerTeam** [comment]
@jdknight My Jenkins file is currently using latest published release through pipenv.
Thanks for the heads up and the proposed workaround. I can wait for the next release  with the current timeframe.
We will publish the doc by "hand" for the time beeing.

**Comment by jdknight** [comment]
Corrections to accepting boolean/numerical configuration entries from the command line are now available on the main branch (via #430) and should be made available next stable release ([v1.4](https://github.com/sphinx-contrib/confluencebuilder/milestone/7)).

**Comment by jdknight** [comment]
v1.4 is now available on PyPI -- marking as closed.

**Comment by ExaneServerTeam** [comment]
@jdknight : thanks a lot for keepeing me uptodate !
