### ISSUE TITLE
Cannot upload via gitlab CI/CD using CI/CD-Variables

### ISSUE THREAD

**Issue by Skatteret** [sphinx-contrib/confluencebuilder#435]
Hi,

I am trying to upload to confluence through gitlab  CI/CD using CI/CD-Variables. I can get it to work when I hardcode confluence_server_user and confluence_server_pass. But when I use CI/CD-variables to CONFLUENCE_USER and set confluence_server_user = os.getenv('CONFLUENCE_USER') then I get that:

_The configured Confluence space does not appear to be valid: AN
Ensure the server is running or your Confluence URL is valid. Also ensure your authentication options are properly set.
Note: Confluence space names are case-sensitive._

I have echo'ed the CONFLUENCE_USER and CONFLUENCE_PASS and they are correct.

Hope that you can help or guide me? Thanks

**Comment by jdknight** [comment]
@Skatteret, this error is usually occurs under two conditions:

1) The space name is incorrect (invalid name or casing does not match).
2) There is no username and no password set (when users attempt anonymous access and are denied).

I suspect it is not the first case, as you have indicated that an original configuration works as expected. A possibility is that the `CONFLUENCE_USER` and `CONFLUENCE_PASS` environment variables are being stripped from the execution of your Sphinx -- are you running under `virtualenv` or `tox` where the environment variables are not being passed through?

One thing you could try is to attempt to fetch environment variables where an exception is raised if these options are not set. That way, you can be sure the values are being appropriately passed in. For example:

```
confluence_server_user = os.environ['CONFLUENCE_USER']
confluence_server_pass = os.environ['CONFLUENCE_PASS']
```

If these values are being passed in as expected, one thing you can do is attempt to generate a report and see a dump of what configuration options are set:

```
python -m sphinxcontrib.confluencebuilder report
```

**Comment by Skatteret** [comment]
Hi thanks for your answer. I was not passing my environment variables to tox. Thanks for the help:)
