### ISSUE TITLE
Support Confluence User/Password + API Key authentication

### ISSUE THREAD

**Issue by arwedus** [sphinx-contrib/confluencebuilder#441]
Hello! My organization has a Confluence instance which uses basic authentication (enterprise user/password) and an additional API key. The API key is sent in a "KeyId" field in the request header. This may be custom, but one of the following is highly appreciated:

- Support for confluence_api_key (including the possibility to ask for it during build, e.g. confluence_ask_api_key), or:
- Support for adding additional header key/value pairs in conf.py.

I see that the same problem has already been solved by [docToolchain publishToConfluence action](https://doctoolchain.github.io/docToolchain/#_publishtoconfluence):

_"apikey"_

_In cases where you have to use full user authorization because of internal confluence permission handling, you need to add the API-token in addition to the credentials. The API-token cannot be added to the credentials as it is used for user and password exchange. Therefore the API-token can be added as parameter apikey, which makes the addition of the token as a separate header field with key: keyId and value of apikey. Example including storing of the real value outside this configuration: apikey = "${new File("/home/me/apitoken").text}"._

**Comment by jdknight** [comment]
@arwedus, thanks for the recommendation. Opted for the latter suggestion by introducing a configuration `confluence_publish_headers` which permits injecting custom header key-values into requests made to the Confluence instance. This should provide the most flexibility for users who need to assign one (or more) header options for any requests made. Depending on the environment, something like this could be done to set, for example, a `keyid` field for all requests:

_(explicit)_
```
confluence_publish_headers = {
    'keyid': '<my-custom-value>',
}
```

_(from a file)_
```
with open('myapitoken', 'r') as f:
    my_api_token = f.read()
...

confluence_publish_headers = {
    'keyid': my_api_token,
}
```

_(from the environment)_
```
import os
...

confluence_publish_headers = {
    'keyid': os.getenv('MY_API_TOKEN'),
}
```





The change (#465) has been added into the main branch and should be made available next stable release (v1.5). If you still experience limitations for your environment after this change, please feel free to let me know.

**Comment by jdknight** [comment]
v1.5 is now available on PyPI -- marking as closed.

**Comment by arwedus** [comment]
works for me, thanks a lot for this feature @jdknight
