### ISSUE TITLE
Table colspec nodes using px instead of %

### ISSUE THREAD

**Issue by r-dgreen** [sphinx-contrib/confluencebuilder#459]
https://github.com/sphinx-contrib/confluencebuilder/blob/57ab6c4d1fd2df8c16953b97d1aa843667722dc0/sphinxcontrib/confluencebuilder/translator/storage.py#L811

Not sure if this is intentional, but it seems inconsistent with how the standard html is built with docutils. With html colspec uses % by default, but here px is used.

**Comment by jdknight** [comment]
@r-dgreen, thanks for reporting this issue. A change (#461) has been added into the main branch that should address this issue and should be made available next stable release (v1.5).

**Comment by jdknight** [comment]
v1.5 is now available on PyPI -- marking as closed.
