### ISSUE TITLE
Update Token Header "nocheck" Value for Compatibility with Jira REST API v3

### ISSUE THREAD

**Issue by StevenMMortimer** [sphinx-contrib/confluencebuilder#470]
## Context

I am currently publishing to a Confluence instance that setup to use v3 of the Jira Cloud Platform REST API. It appears that it has been fairly stable since early 2020 and is used for production in many cases. However, one change from v2 to v3 appears to be the `X-Atlassian-Token` header, which accepts the value `no-check` instead of `nocheck`. 

https://github.com/sphinx-contrib/confluencebuilder/blob/52cee9b50925cba4ba8162bdc8824db8c31894c3/sphinxcontrib/confluencebuilder/rest.py#L134-L141

This is causing confluencebuilder to generate the following warning in the logs: 

>2021-05-25 17:59:56,834 WARN [http-nio-8080-exec-598] [common.security.jersey.XsrfResourceFilter] hasDeprecatedHeaderValue Use of the 'nocheck' value for X-Atlassian-Token has been deprecated since rest 3.0.0. Please use a value of 'no-check' instead.

## Potential Solution

This could be part of a larger change needed to support v3, but a small fix would be updating this one value that is currently hardcoded to the newer accepted value `no-check`.

**Comment by jdknight** [comment]
Interesting.

For Confluence's REST API, typically it has always been [documented](https://developer.atlassian.com/cloud/confluence/rest/api-group-content---attachments/#api-api-content-id-child-attachment-put) with an expected value of `nocheck`:

> Note, you must set a X-Atlassian-Token: nocheck header on the request for this method, otherwise it will be blocked. This protects against XSRF attacks, which is necessary as this method accepts multipart/form-data.

However, there is at least [one example](https://developer.atlassian.com/server/confluence/confluence-rest-api-examples/#upload-an-attachment) (when explicitly looking a Confluence REST API examples) where `no-check` is referenced:

> curl -v -S -u admin:admin -X POST -H "X-Atlassian-Token: no-check" -F ...

Examining some Confluence sources (v6.7.x) shows that `no-check` is being used in its implementation and some unit tests. Oddly, there does not appear to be anything explicit checking for `nocheck` -- only some cases where it may automatically inject a `no-check` header if it detects some POST cases (is that what Confluence is always doing with these calls?).

Maybe the Confluence REST API was never updated to reflect the recommended `no-check` value? Sanity checking against the older supported Confluence server version (v6.13.x) appears to show attachments working as expected when changing this extension's implementation from `nocheck` to `no-check` -- so, maybe it is safe to do this for long term use? I am all for this change if all supported Confluence instances work as expected when publishing new attachments (Cloud and Server v6.13+; something I can go ahead at test with a local modification). If you want to prepare a pull request with this case and all my local testing works as expected, I do not see an issue merging it in; else wise I can prepare a formal commit after my tests.

I am a bit confused here on how one is even able to use the Jira Cloud Platform REST API to interact with a Confluence instance. If you happen to have additional information on how this is achieved, it could be useful for future development/testing.

**Comment by jdknight** [comment]
Went ahead with a change -- now always applying the `X-Atlassian-Token: no-check` for all REST requests from this extension. Sanity checking against all supported Confluence versions appears to show no negative effects. This change will be available in the next stable release (v1.6).

A workaround, if needed -- the environment variable `CONFLUENCEBUILDER_LEGACY_NOCHECK` can be used to fallback to the legacy `nocheck` value.

@StevenMMortimer, thanks again for reporting this.

**Comment by jdknight** [comment]
v1.6 is now available on PyPI -- marking as closed.
