### ISSUE TITLE
Class member documentation has conversion issues

### ISSUE THREAD

**Issue by machinekoder** [sphinx-contrib/confluencebuilder#480]
I get some messages on Confluence Cloud stating that there are conversion issues:
![image](https://user-images.githubusercontent.com/1467368/121871963-0659a180-cd05-11eb-8a82-8fd93e08d7ee.png)

Any ideas what's the source of the problem?

"Learn More" links to https://support.atlassian.com/confluence-cloud/docs/convert-pages-to-the-new-editor/#Convertpagestotheneweditor-WhatACTUALLYhappenswhenyourcontentisconverted

**Comment by jdknight** [comment]
The `confluencebuilder` extension focuses on building storage format ("older editor") documentation that is compatible on supported Confluence instances that best represent patterns in other stock Sphinx builder types. How Atlassian deals with converting valid storage format content to their new editor is not something this extension tries to manage (a lot of things to consider here). At this time, this extension only supports storage format content.

For users interested in publishing content into the new ADF format ("new editor"), there will be a new builder provided by this extension soon (~August). This effort is being tracked in #347.
