### ISSUE TITLE
\b in code-block directive within docstring causes API error

### ISSUE THREAD

**Issue by capfish** [sphinx-contrib/confluencebuilder#482]
I have a [click](https://click.palletsprojects.com/en/8.0.x/) application and am using the [sphinx-click](https://sphinx-click.readthedocs.io/en/latest/) extension to generate the man pages in sphinx.   I have a docstring that looks something like this

```
@click.command()
@click.argument(arg1)
def my_command(arg1):
    """
    Arg1 is a path to a json file with the following schema
    \n
    .. code-block:: text

        \b
        {
            "field1": "value1",
            "field2": "value2"
        }
    """
        
```

The `\b` is necessary for the generated click help formatting see: (https://drive.google.com/file/d/120hCVeWQBiWwboD1H5gdQIA-Nq2n2y2X/view?usp=sharing)

However, the `\b` creates an API error when pushing to confluence

```
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://acuityam.atlassian.net/wiki/rest/api
API: content
DATA: {
  "statusCode": 400,
  "data": {
    "authorized": false,
    "valid": true,
    "errors": [],
    "successful": false
  },
  "message": "com.atlassian.confluence.api.service.exceptions.BadRequestException: Error parsing xhtml: Unexpected character 'p' (code 112) expected '>'\n at [row,col {unknown-source}]: [17,25]"
}
```

Removing the `\b` makes the error go away, but the help text formatting in the cli tool is ruined.  Is there away to include the `\b` but prevent the api error?

```
> sphinx-build-confluence report
(system)
 platform: Windows-10-10.0.19041-SP0
   python: 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)]
   sphinx: 4.1.2
 requests: 2.26.0
  builder: 1.5.0

(configuration)
confluence_asset_override: True
confluence_disable_notifications: True
confluence_page_hierarchy: True
confluence_publish: True
confluence_publish_root: (set)
confluence_server_pass: (set)
confluence_server_url: https://<removed> (cloud)
confluence_server_user: (set)
confluence_space_name: (set; upper)

(error loading configuration)
unable to load configuration

(confluence instance)
 connected: no
```

Thanks!

**Comment by jdknight** [comment]
It appears there are two issues with the `confluencebuilder` extension:

1. Content parsing is not removing unsupported characters that a Confluence instance cannot handle.
2. Line hints for no-wrapping are not handled properly.

The second may be just a trivial fix to the storage format translator; however, additional testing should be performed to ensure there are no cases where a line node should not be breaking:

```
    def depart_line(self, node):
        self.body.append('<br />')
```

The testing performed for `sphinx-click`-supported documentation was done using alternative samples (note that the sample provided in OP appears to be access restricted). The example code used involved:

```
(hello_world.py)
@greet.command()
def test():
    """test command
    
    \b
        a:  line one
        b:  line two
    """
    pass

(index.rst)
.. click:: hello_world:test
  :prog: hello-world
  :nested: full
```

With the proposed changes mentioned above, the generated content for Confluence appears to match the same visual/pattern observed when building with an `html` builder.

---

Note that with the example provided in the original issue (as follows):

```
    .. code-block:: text

        \b
        {
            "field1": "value1",
            "field2": "value2"
        }
```

It does not appear to be correct (please correct me if I am wrong here). Passing the `\b` character into a code block is not related to click's non-wrapping hint. This example indicates that there is a desire to inject the `\b` character at the start of this code block (which, from the publishing error, does not look to be supported by Confluence). Either the example case should have been `\\b` or the example is just intended to show a breaking case of the publication issues. To correct this (noted as issue 1; above), there should be some additional character filtering/cleanup for generated storage-format documentation.

**Comment by capfish** [comment]
Hi sorry, that link that's protected was just supposed to be a link to the relevant click docs https://click.palletsprojects.com/en/8.0.x/documentation/#preventing-rewrapping

And yes, you're right about the example code.  It is just what I ended up using and I have a script that removes either the `-- code-block:: text` or the `\b` depending on if I'm building the docs with sphinx or building the actual cli tool installer so that both the cli tool man pages and the confluence pages have a readable layout.  Thanks!

**Comment by jdknight** [comment]
@capfish, thanks for the information.

Just merged into two changes into the main branch (#488, #489). It is believed that they will resolve the issue being experienced here. Please feel free to leave a comment if you wish to try them out. If all goes well, they will be available in the next stable release of this extension.

**Comment by jdknight** [comment]
v1.6 is now available on PyPI -- marking as closed.

**Comment by jdknight** [comment]
@capfish, a change has been introduced in #518 (available via a bleeding edge install) which should address this issue.

For example, an extended modification of the provided `test` command above:

```
@greet.command()
def test2():
    """test command
    
    \b
            zzz
        a:  line one
                aaa
        b:  line two
            sub_b: line three
                aasf
    """
    pass
```

Produces the following output on a Confluence Cloud instance:

![image](https://user-images.githubusercontent.com/1834509/139519935-80ee25a7-a300-49fa-9560-dac624403666.png)

Feel free to try it out -- and please let me know if I may have overlooked anything.

**Comment by capfish** [comment]
The bleeding edge install does the trick!  Thank you so much!

**Comment by jdknight** [comment]
For reference, v1.7 (which includes the additional corrections to alignment) is now available on PyPI.
