### ISSUE TITLE
confluence_metadata directive breaks html build

### ISSUE THREAD

**Issue by theavey** [sphinx-contrib/confluencebuilder#505]
Hi there:

If I include "sphinxcontrib.confluencebuilder" in my extensions, include a `confluence_metadata` directive in my documentation, and then try to `.\make.bat html ...`, I get a fatal error:

    Exception occurred:
      File "C:\...\lib\site-packages\sphinx\writers\html5.py", line 801, in unknown_visit
        raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
    NotImplementedError: Unknown node: confluence_metadata

sphinx: 4.2.0
sphinxcontrib-confluencebuilder: 1.6.0
python: 3.8.12

I can `make confluence` just fine, but I don't think adding an unrelated extension should break my build of html docs. I would almost mind less (though it would be harder to deal with) if that directive just broke the build when I did not include the "sphinxcontrib.confluencebuilder" extension.

If you need more info or anything, please let me know.

**Comment by jdknight** [comment]
v1.7 is now available on PyPI -- marking as closed.
