### ISSUE TITLE
sphinxcontrib.confluencebuilder.exceptions.ConfluenceUnreconciledPageError encountered in Confluence 7.4.11 - not related to migration

### ISSUE THREAD

**Issue by RobertSeeger** [sphinx-contrib/confluencebuilder#528]
### Problem description
In an ongoing development of a large-scale Sphinx to Confluence publishing, which runs inside our application with a built-in Python 3.8 interpreter, I recently encounter a `sphinxcontrib.confluencebuilder.exceptions.ConfluenceUnreconciledPageError` when trying to publish the index page, which is quite huge because it covers over 3000 module pages that are mostly created with the autodoc extension. Publishing of the remaining pages then is suspended.

In the publishing log, I found the note:

> If this is observed on Confluence v6.x, v7.3.3 or higher, please report this issue to the developers of the Confluence builder extension.

and the reference to [https://jira.atlassian.com/browse/CONFSERVER-59196](https://jira.atlassian.com/browse/CONFSERVER-59196).

While this issue is related to cases encountered after an upgrade from Confluence v6.x to v7.x, I like to stress that my case is not related to such an upgrade. Our test instance is running 7.4.11 and has been doing so before the first attempt was made to create the page that now raises the error.

In addition, the suggested workaround of just viewing the page did not resolve the problem.

### Excerpt of the build log
_(the XHTML in field "value" has been removed as this page is really huge - the source file is attached as [index.conf.txt](https://github.com/sphinx-contrib/confluencebuilder/files/7460845/index.conf.txt))_

Traceback (most recent call last):
  File "D:\Program Files\Python38\lib\site-packages\sphinxcontrib\confluencebuilder\publisher.py", line 742, in _updatePage
    self.rest_client.put('content', page['id'], updatePage)
  File "D:\Program Files\Python38\lib\site-packages\sphinxcontrib\confluencebuilder\rest.py", line 186, in put
    raise ConfluenceBadApiError(errdata)
sphinxcontrib.confluencebuilder.exceptions.ConfluenceBadApiError: ---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 501
URL: https://confluence-test.experiment.germanedge.testyard.cloud/rest/api
API: content
DATA: {
  "statusCode": 501,
  "message": "Unable to save changes to unreconciled page ContentId{id=68791363}",
  "reason": "Not Implemented"
}
{
  "type": "page",
  "title": "Welcome Page 7.6.0",
  "body": {
    "storage": {
      "representation": "storage",
      "value": _(removed from report)_
    }
  },
  "space": {
    "key": "ORSDOC"
  },
  "id": "68791363",
  "version": {
    "number": 16,
    "minorEdit": true
  },
  "metadata": {
    "labels": [
      {
        "name": "orsoft-release-to-7-6-0"
      },
      {
        "name": "orsoft-release-from-7-6-0"
      }
    ]
  },
  "ancestors": [
    {
      "id": "68791361"
    }
  ]
}
---

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python38\lib\site-packages\sphinx\cmd\build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "D:\Program Files\Python38\lib\site-packages\sphinx\application.py", line 335, in build
    self.builder.build_all()
  File "D:\Program Files\Python38\lib\site-packages\sphinx\builders\__init__.py", line 305, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "D:\Program Files\Python38\lib\site-packages\sphinx\builders\__init__.py", line 415, in build
    self.finish()
  File "D:\Program Files\Python38\lib\site-packages\sphinxcontrib\confluencebuilder\builder.py", line 601, in finish
    self.publish_doc(docname, output)
  File "D:\Program Files\Python38\lib\site-packages\sphinxcontrib\confluencebuilder\builder.py", line 458, in publish_doc
    uploaded_id = self.publisher.storePage(title, data, parent_id)
  File "D:\Program Files\Python38\lib\site-packages\sphinxcontrib\confluencebuilder\publisher.py", line 535, in storePage
    self._updatePage(page, page_name, data, parent_id=parent_id)
  File "D:\Program Files\Python38\lib\site-packages\sphinxcontrib\confluencebuilder\publisher.py", line 745, in _updatePage
    raise ConfluenceUnreconciledPageError(
sphinxcontrib.confluencebuilder.exceptions.ConfluenceUnreconciledPageError: ---
Unable to update unreconciled page: Welcome Page 7.6.0 (id: 68791363)

Unable to update the target page due to the Confluence instance reporting an unreconciled page. A workaround for this is to manually browse the page using a browser which will force Confluence to reconcile the page. A link to the page is a follows:

   https://confluence-test.experiment.germanedge.testyard.cloud/pages/viewpage.action?pageId=68791363

If this is observed on Confluence v6.x, v7.3.3 or higher, please report this issue to the developers of the Confluence builder extension.

See also: https://jira.atlassian.com/browse/CONFSERVER-59196

(details: ---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 501
URL: https://confluence-test.experiment.germanedge.testyard.cloud/rest/api
API: content
DATA: {
  "statusCode": 501,
  "message": "Unable to save changes to unreconciled page ContentId{id=68791363}",
  "reason": "Not Implemented"
}
{
  "type": "page",
  "title": "Welcome Page 7.6.0",
  "body": {
    "storage": {
      "representation": "storage",
      "value": _(removed from report)_
    }
  },
  "space": {
    "key": "ORSDOC"
  },
  "id": "68791363",
  "version": {
    "number": 16,
    "minorEdit": true
  },
  "metadata": {
    "labels": [
      {
        "name": "orsoft-release-to-7-6-0"
      },
      {
        "name": "orsoft-release-from-7-6-0"
      }
    ]
  },
  "ancestors": [
    {
      "id": "68791361"
    }
  ]
}
---
)
---

sphinxcontrib.confluencebuilder error:
---
Unable to update unreconciled page: Welcome Page 7.6.0 (id: 68791363)

Unable to update the target page due to the Confluence instance reporting an unreconciled page. A workaround for this is to manually browse the page using a browser which will force Confluence to reconcile the page. A link to the page is a follows:

   https://confluence-test.experiment.germanedge.testyard.cloud/pages/viewpage.action?pageId=68791363

If this is observed on Confluence v6.x, v7.3.3 or higher, please report this issue to the developers of the Confluence builder extension.

See also: https://jira.atlassian.com/browse/CONFSERVER-59196

(details: ---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 501
URL: https://confluence-test.experiment.germanedge.testyard.cloud/rest/api
API: content
DATA: {
  "statusCode": 501,
  "message": "Unable to save changes to unreconciled page ContentId{id=68791363}",
  "reason": "Not Implemented"
}
{
  "type": "page",
  "title": "Welcome Page 7.6.0",
  "body": {
    "storage": {
      "representation": "storage",
      "value": _(removed from report)_
    }
  },
  "space": {
    "key": "ORSDOC"
  },
  "id": "68791363",
  "version": {
    "number": 16,
    "minorEdit": true
  },
  "metadata": {
    "labels": [
      {
        "name": "orsoft-release-to-7-6-0"
      },
      {
        "name": "orsoft-release-from-7-6-0"
      }
    ]
  },
  "ancestors": [
    {
      "id": "68791361"
    }
  ]
}
---
)
---

### Report output from sphinxcontrib.confluencebuilder report
(system)
 platform: Windows-10-10.0.19041-SP0
   python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
   sphinx: 1.8.4
 requests: 2.26.0
  builder: 1.6.0

(configuration)
confluence_append_labels: False
confluence_asset_force_standalone: True
confluence_asset_override: True
confluence_disable_autogen_title: True
confluence_disable_notifications: True
confluence_disable_ssl_validation: True
confluence_global_labels: (set)
confluence_header_file: conf_header.tpl
confluence_ignore_titlefix_on_index: True
confluence_page_hierarchy: True
confluence_parent_page: (set)
confluence_prev_next_buttons_location: both
confluence_publish: True
confluence_publish_postfix:  7.6.0
confluence_remove_title: False
confluence_server_pass: (set)
confluence_server_url: https://<removed>
confluence_server_user: (set)
confluence_space_name: (set; upper)
confluence_title_overrides: {'index': 'Welcome Page 7.6.0'}

(error loading configuration)
unable to load configuration

(confluence instance)
 connected: no

- _"(error loading configuration)" is due to the specific nature of the development, which relies on the sphinx build to be executed inside our application. Otherwise it creates a lot of import errors._

**Comment by RobertSeeger** [comment]
I have also attached the source RST of the index page. As you can see, it uses the `.. confluence_expand::` directive in order to create collapsible toctrees.
[index.rst.txt](https://github.com/sphinx-contrib/confluencebuilder/files/7460992/index.rst.txt)

**Comment by jdknight** [comment]
@RobertSeeger, thanks for mentioning this. An unreconciled page is something failing on the server side of a Confluence instance. We added that warning before as an informational message users using a subset Confluence instances which had observed a fault in processing page updates (#314). Looks like you are experience a same/similar issue on the Confluence instance you are publishing to.

I did a quick scan of the Confluence JIRA's and found these two issues:

- https://jira.atlassian.com/browse/CONFCLOUD-72349
- https://jira.atlassian.com/browse/CONFSERVER-69310

It looks like unreconciled errors are happening for others as well (at least some some v7.4.+ version and Cloud).

When you state:

> before the first attempt was made to create the page that now raises the error.

Are you saying that the first push event works; and then future pushes fail?

It looks like one of the issues indicates that deleting a page and then creating a new one appears to prevent a risk of an unreconciled (if the server cannot handle the upgrade). If that is the case, we can try to modify this extension to fallback to performing a delete/update if an update request fails.

Another comment I see in an issue is that a user indicates that if a publish event is updated to include a forced status of `current`, it could resolve their API PUT request:

```
../rest/api/content/PAGE_ID?status=current
```

It seems like dealing with a status field is hinted at dealing with various types of a page (current, draft, etc.). I wonder if there is sometimes issues where a large page is being edited/etc. and then an update request comes along and Confluence is not happy. We could try adjusting this extension's PUT command to do the same (to be explicit). A local test with it now shows the command works; but I will try to find a way to replicate the specific unreconciled error (which is not something I have personally observed yet).

---

At this time, you are for sure not doing anything wrong. But unfortunately, I do not have a specific solution to your issue. The only recommendations I could suggest at this time are:

1. If you are a tech-savvy, you could attempt to change this extension's [`sphinxcontrib/confluencebuilder/publisher.py#L818`](https://github.com/sphinx-contrib/confluencebuilder/blob/ff896bd39c94bb29bdd266a3d7a47b1fda77a0ef/sphinxcontrib/confluencebuilder/publisher.py#L818) in your local instance and see if it resolves your issue. Specifically, changing:
```
self.rest_client.put('content', page['id'], updatePage)
```
to
```
self.rest_client.put('content', page['id'] + '?status=current', updatePage)
```

Alternatively, I created a branch with the above change which can be lazily installed via this command:

```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git@unreconciled-test
```

2. You could attempt to delete the main/index page and re-try the publish request. If it works first pass, there are changes this extension can make to better handle this Confluence issue.

---

Summary of things can be be done in this extension:

- (investigate) Possibly attempt to delete and re-create a new page if unreconciled  page is detected.
- If an update event fails on a temporary server-side lock, it retries. Possibly update this so other failure attempts can be retried as well?
- Update the unreconciled exception in this extension to also include this newly observed issue.

**Comment by RobertSeeger** [comment]
@jdknight thanks a lot for the fast reaction.

> Are you saying that the first push event works; and then future pushes fail?
Several pushes worked and then starting this week suddenly I had this problem. Because the error happened on the index page, publishing of all other pages did not happen anymore.
I am constantly fine-tuning and improving the Sphinx generation and publishing process, which was previously only targeting the HTML builder, such as the preprocessing of docstrings with the autodoc extension (we have been using Epydoc for many years and are only gradually migrating our source code documentation to Sphinx Syntax, so we need to convert those docstrings on the fly) and the generation of good unique page titles.

Meanwhile it turned out that my huge index page is somehow "broken beyond repair" - all attempts to edit, revert or delete it in the web browser failed. I did not try to delete it via REST API as this would have rendered its > 4000 descendants "fatherless" and clutter the page hierarchy (this is why the suggestion "Possibly attempt to delete and re-create a new page if unreconciled page is detected" seems slightly risky. I haven't found a REST API call that would delete a page and its descendants).

- I believe the page must have been broken in one of my previous publishing runs when I had to cancel the python process via Task Manager

So what I did was to change the name of the index page in `confluence_title_overrides` and run the publishing again. This way, the 4000 pages were neatly rearranged into descendants of the new index page. The old index page remains alone and untouched. Luckily I am still on a test instance of Confluence and using a dedicated test space.
I did several more runs since then and did not encounter that situation again.

So for now - fingers crossed - my immediate problem has been resolved.

I think explicitly adding `status=current` to the PUT request is a good idea, as this should be the target status for the kind of mass-publishing this extension does.

**Comment by jdknight** [comment]
@RobertSeeger, I am glad you got something working for your use case.

I have tried triggering an unreconciled error state with some limited Confluence Cloud tests, but more so against a local Confluence server. Although, currently, my attempts to spawn such an issue with large page changes has yet to produce this issue. I'll try a few more things to later to see if there is an easy way to produce this, but I still do not know how much this extension can do here.

Changes have been made into this extension to possibly help with an unreconciled page. As mentioned above, page update (PUT) requests have been modified to explicitly set the `status` option. Since it is the default option, I cannot see it adding any harm -- and maybe in the odd case where Confluence adjusts the request to do some automatic management, the forced `current` value can be a more aggressive indicating to just update page. Limited testing shows expected publishing attempts with Cloud and a server version -- but more extensive sanity checks will be done when a release is made.

Also, if an unreconciled page is detected, a delayed retry attempt will be performed as well. This extension already performs an extremely crude retry attempt when Confluence reports a threading lock condition -- and the logic has been tweaked to retry also when an unreconciled page error is detected as well (this could be improved over time).

Finally, the unreconciled page exception message has been updated to no longer reflect that this is an older bug. Based on the other unreconciled issues reported on Confluence's JIRA pages, the message is a bit more generic -- indicating what the issue may be, some tips a user can try and points to this issue for more information.

If you do experience other issues like this, I would be curious to know. Hopefully updates can be made to this extension to provide a better user experience for all.

---

On a related note to your comment on deleting the broken index page, this extension does provide a `wipe` command to help delete pages for a configured space. The command is undocumented on the current release and only supports wiping all pages for a configured space, but the bleeding edge sources does provide support to delete with consideration of a configured parent. You can consult the documentation [here](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/tips/#wiping-a-space) for more information (if desired).

**Comment by jdknight** [comment]
Marking this issue as "pending next release" since it has incorporated changes to help better mitigate unreconciled pages (some retries and improved error messages). There is not much this extension can do to help prevent these scenarios (when last investigated), it this issue will be closed when the next release is made. Feel free to comment otherwise if this is believed to be in err.

**Comment by jdknight** [comment]
v1.8 is now available on PyPI -- marking as closed.
