### ISSUE TITLE
Confluence Documentation is created in the form of "blogs" instead of "pages" using sphinxcontrib-confluence

### ISSUE THREAD

**Issue by divyankm** [sphinx-contrib/confluencebuilder#600]
Hi,

I am building confluence documentation using sphinxcontrib-confluencebuilder.
I am having 20+ python scripts and its documentation is getting generated in confluence in the for of "blogs", but I want it to be created in "pages".

Documentation is getting generated in the confluence but it is documented in the form of "blogs" instead of "pages". 

I am using sphinx version-4.2.0, sphinxcontrib-confluencebuilder -1.7.0.

Pls, let me know if any config is required to generate documentation in "pages".

conf.py-

`
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinxcontrib.confluencebuilder'
]

confluence_publish = True
confluence_space_key = 'DOCS'
confluence_server_url = 'https://<...>.atlassian.net/wiki/'
confluence_server_user = '<>'
confluence_server_pass = '<>'
#confluence_parent_page = 'API Docs'

templates_path = ['_templates']

exclude_patterns = []

html_theme = 'alabaster'

html_static_path = ['_static']
`
Ref link-
https://towardsdatascience.com/publish-python-project-documentation-on-confluence-html-using-sphinx-fad3a98b8eeb
https://community.atlassian.com/t5/Confluence-questions/Confluence-Documentation-is-created-in-the-form-of-blogs-instead/qaq-p/1899730?utm_source=atlcomm&utm_medium=email&utm_campaign=mentions_answer&utm_content=topic 

Thank you!!!

**Comment by jdknight** [comment]
@divyankm, any chance we can get a bit more information on the issue?

The configuration you have provided looks like. This extension [will only ever create `page` types through an API call](https://github.com/sphinx-contrib/confluencebuilder/blob/6313757831acf1edcdc8ffa2912491253299c892/sphinxcontrib/confluencebuilder/publisher.py#L791), so am I not sure how a `blog` type would be created (and this extension does not provide a way to make blog-based content).

Are you seeing pages published by this extension being added under the "Blog" navigational section under various dates?

![image](https://user-images.githubusercontent.com/1834509/147964502-7934a2a6-94f7-44e9-9602-af7bbfed77d4.png)

Or is there something else happening?

**Comment by divyankm** [comment]
Hi @jdknight 

I checked in the "blog" tab page name-'interpolate' is not present there (snap1). It is present on the pages section only (snap2).

While I run "make confluence", the pages are created in the form of blogs and I need to convert it manually from blogs to pages.

I am adding snap of pages which is blog is formatted differently than pages. While the document is in page format I am getting the option to convert it into the blog, but while "blog" is getting generated that option is not there.


`
$ make confluence
Running Sphinx v4.2.0
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [confluence]: targets for 0 source files that are out of date
updating environment: [config changed ('confluence_add_secnumbers')] 2 added, 0 changed, 0 removed
reading sources... [100%] interpolate
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] interpolate
publishing documents... [100%] interpolate
Publish point: https://<...>/wiki/spaces/DOCS/pages/9263383242
building intersphinx... done
build succeeded.
`

snap1-
![image](https://user-images.githubusercontent.com/80899863/148013239-284282b3-45eb-45bd-9bfa-b6e07e67dd20.png)

snap2-

![image](https://user-images.githubusercontent.com/80899863/148013416-4ce84f63-149c-48fd-9a24-125ce34f02cc.png)

snap3-
Page format of "interpolate" doc which is getting converted from blog manually.

![image](https://user-images.githubusercontent.com/80899863/148014262-6fb086c9-4de1-4708-a283-aab9a954f937.png)


snap4-
blog generated after using the command "make confluence".

![image](https://user-images.githubusercontent.com/80899863/148014498-46657fc3-8ab3-4824-bb72-e2a639c20738.png)

**Comment by divyankm** [comment]
Update-

Update-


After downgrading version sphinxcontrib-confluencebuilder from 1.7.0 to 1.6, Pages are getting created in new editor and docs is getting created successfully.

`pip install sphinxcontrib-confluencebuilder==1.6`

[https://community.atlassian.com/t5/Confluence-questions/Confluence-Documentation-is-created-in-the-form-of-blogs-instead/qaq-p/1899730?utm_source=atlcomm&utm_medium=email&utm_campaign=accept_as_solution_reminder&utm_content=topic#U1903844](Confluence)

**Comment by jdknight** [comment]
Ah, OK -- I understand now.

The explicit use of the legacy editor [is done intentionally](https://github.com/sphinx-contrib/confluencebuilder/blob/6313757831acf1edcdc8ffa2912491253299c892/sphinxcontrib/confluencebuilder/publisher.py#L799-L808). Confluence's new editor does not support all features provided by this extension to handle the various capabilities of Sphinx-supported markup (e.g. nested tables). It is unknown when Atlassian changes the default publishing request to use the new editor, but when this occurred, it broke some documentation sets relying on the more complex Sphinx capabilities. We adjusted this extension to force to use the old editor to prevent these issues.

At this time, there is not an official way to force the use of the newer editor (aside from manually adjusting the implementation in your instance and assuming Confluence will handle all the storage format outputs generated). There is an intent to support the newer editor through a newer builder, which is captured in #347. The reason for the second builder is to provide existing users the same capabilities to use Sphinx supported-markup with existing/complex documentation sets, and giving users the freedom to use a newer/limited builder with simpler documentation with the newer style. The process to supporting the newer builder is taking some time though -- supporting the ADF format requires some changes to how this extension works (specifically, with attachment/image handling). Also, there are a lot of features to check and add to unit testing to ensure we maximize as much capability provided by Sphinx that can be supported using Confluence's new editor. At this time, there is no timeline for its release.

**Comment by jdknight** [comment]
There is now a new issue (see #642) tracking all the notables to consider when supporting the EditorV2 capabilities. Will mark this issue as closed; users interested in tracking the planned support for the new editor should now refer to #642 instead.
