### ISSUE TITLE
confluence_root_homepage doesn't appear to work for personal spaces

### ISSUE THREAD

**Issue by rtdean** [sphinx-contrib/confluencebuilder#612]
Making use of Confluence Cloud, attempting to manage my entire personal wiki space with sphinx-confluencebuilder.  When I set `confluence_root_homepage = True`, I get an error from Confluence.

*sphinx-build-confluence report*
```
(system)
 platform: macOS-10.15.7-x86_64-i386-64bit
   python: 3.9.10 (main, Jan 24 2022, 09:39:27) [Clang 12.0.0 (clang-1200.0.32.29)]
   sphinx: 4.4.0
 requests: 2.27.1
  builder: 1.7.1

(configuration)
confluence_publish: True
confluence_purge: True
confluence_server_pass: (set)
confluence_server_url: https://<removed> (cloud)
confluence_server_user: (set)
confluence_sourcelink: {'type': 'github', 'owner': '<removed>, 'repo': '<removed>', 'container': '<removed>', 'version': 'master'}
confluence_space_key: (set; user)

(confluence instance)
 connected: yes
   fetched: yes
   decoded: yes
    parsed: yes
      type: confluence
   version: 1000.0.0-f64f6b1f49c9
     build: 6452
```

The error I received is as follows:

```
Unsupported Confluence API call

An unsupported Confluence API call has been made. See the following
details for more information:

REQ: PUT
RSP: 400
URL: https://<removed>.atlassian.net/wiki/rest/api
API: space
DATA: {
  "statusCode": 400,
  "data": {
    "authorized": true,
    "valid": false,
    "errors": [
      {
        "message": {
          "translation": "Cannot change space type from personal to global or vice versa",
          "args": []
        }
      }
    ],
    "successful": false
  },
  "message": "com.atlassian.confluence.api.service.exceptions.BadRequestException: Cannot change space type from personal to global or vice versa"
}
```

I was able to go into the confluence settings for my personal space and set my homepage to the appropriate document (and commented out my `confluence_root_homepage` setting in `conf.py`, but I thought I'd raise the bug in case someone else runs into the issue (and, of course, I'd love to manage this all in one place...)

**Comment by jdknight** [comment]
Based on some testing, it looks like Confluence's API is defaulting the `type` field for a [space update](https://developer.atlassian.com/cloud/confluence/rest/api-group-space/#api-wiki-rest-api-space-spacekey-put) to be of a `global` type, instead defaulting it to a space's existing type.

Merged in a change from #613 which should fix this -- where we now force an explicit space type value when attempting to update the homepage field. This issue looks to only be an issue with Confluence Cloud (Confluence server version 7.2.x and 7.14.x appear to be fine; before and after the referenced changes were introduced). Please free to try out the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) to see if this resolves your issue.

**Comment by jdknight** [comment]
fyi | Also have a ticket registered here: [CONFCLOUD-73548](https://jira.atlassian.com/browse/CONFCLOUD-73548)

**Comment by jdknight** [comment]
v1.8 is now available on PyPI -- marking as closed.
