### ISSUE TITLE
Support content version.message / page history comment field

### ISSUE THREAD

**Issue by falxcerebri** [sphinx-contrib/confluencebuilder#629]
Scenario: To keep my generated confluence docs in sync with project releases, I'd like to have my confluence page history somewhat related to `git describe --tags` (or something else for other projects). To do so I'd need either to modify `updated_page['version']['number']` or add version comment. Apparently confluence supports version comment:

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/4255034/156019029-123262b2-1ae5-4809-9b27-b1815fc615f0.png">

To fill in the comment column at the moment it's required to either use available UI while editing or make an API call (see [here](https://community.atlassian.com/t5/Confluence-questions/How-to-add-comment-in-page-history/qaq-p/629892))

It looks like this can be achieved by adding another parameter and extending the `version` object. I'll submit PR this week.

**Comment by falxcerebri** [comment]
Thanks @mkostyla !
@jdknight would you spare some time to take a look? We'd love to use this feature at our company.

**Comment by jdknight** [comment]
Changes have been added in #633 (thanks to @mkostyla) to support users the ability to hint on the version field through a configuration entry. This change has been added into the main branch and should be made available next stable release (v1.8). Users needing to use this feature before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/install/#development-installation) of this extension can be installed.

**Comment by jdknight** [comment]
v1.8 is now available on PyPI -- marking as closed.
