### ISSUE TITLE
Workaround for unsupported extensions 

### ISSUE THREAD

**Issue by egemenkarabyk** [sphinx-contrib/confluencebuilder#639]
As it can be seen from https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/features/, some of the very useful extensions we have in html builder are not supported by confluence builder. 
Is there any workaround to set specific themes for the page as we have in html_theme? 
Or is there any quick way to create links from documentation to source code as it is in sphinx.ext.viewcode extension(which is not also supported in confluence builder)?

**Comment by jdknight** [comment]
> Is there any workaround to set specific themes for the page as we have in html_theme?

This extension does not have full control over the look-and-feel of the content being rendered on a Confluence instance. Confluence provides an API which can enable users to provide document data, and structure hints for said data, to be rendered for a given page. Theming for a Confluence space/instance is [managed through site administration of a Confluence instance](https://confluence.atlassian.com/doc/working-with-themes-151522.html). If you are looking to apply a custom theme to a site/instance, you can try investigating Atlassian's documentation on [Writing a Confluence theme](https://developer.atlassian.com/server/confluence/writing-a-confluence-theme/).

> [Is] there any quick way to create links from documentation to source code as it is in sphinx.ext.viewcode extension(which is not also supported in confluence builder)?

As you have already mentioned, yes, there is no support provided by this extension to generating links between documentation to source code (for code examples). While it would be nice to take advantage of capabilities provided by the [sphinx.ext.viewcode](https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html) extension, the extension's implementation is [limited to only a subset of builder types](https://github.com/sphinx-doc/sphinx/blob/9141464b8bcd4f2ade902107872fd001655a5131/sphinx/ext/viewcode.py#L58-L66).

**Comment by jdknight** [comment]
As discussed in an above comment, theming is outside this extensions scope and there is not much we can do for interacting with extensions that do not provide a means to interface with them. Users who are interested in trying to get support internal Sphinx extensions that could work with this extension are encouraged to introducing pull requests for these extensions. For example, see [the progression](https://github.com/sphinx-doc/sphinx/pull/10585) towards supporting `sphinx.ext.linkcode` extension. For other extensions, it is recommended to bring up a discussion on their mailing lists/issue systems if there is a limitation that Confluence cannot manage.

With the above in mind, will be marking this issue a closed.
