### ISSUE TITLE
Double quotes in code-block title doesn't work

### ISSUE THREAD

**Issue by vills** [sphinx-contrib/confluencebuilder#649]
I think i found a bug when using double quotes in title (caption) in `code-block` block.

For example:
```
.. code-block:: python
   :caption: example "import everything"

   from module import *
```

`caption` attribute value renders in confluence as default paragraph text right before code block without title.

Versions:
- sphinx: 4.5.0
- sphinxcontrib-confluencebuilder: 1.8.0
- confluence: 7.4.11

Thanks!

**Comment by jdknight** [comment]
Thanks for the information/example.

Changes have been added in #651 to correct the issue where in some scenarios the caption value would not be cached and applied to a built code macro. This change has been added into the main branch and should be made available next stable release. If blocked by this issue before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

**Comment by vills** [comment]
Checked code from master branch and it works correct now. Much thanks!

**Comment by jdknight** [comment]
v1.9 is now available on PyPI -- marking as closed.
