### ISSUE TITLE
Labels configured with confluence_global_labels are not set on the initial build, only on an update build (1.8.0)

### ISSUE THREAD

**Issue by RobertSeeger** [sphinx-contrib/confluencebuilder#655]
### Problem Description
**Expected:**

- labels are set in an initial build, that means on pages created by the build, as well as in an update build, that means on pages updated by the build 

**Observed:**

- labels are not set in an initial build, that means on pages created by the build, independent of the setting of confluence_append_labels to True or False
- labels are only set in an update build, that means on pages updated by the build - this is independent of whether the source content has changed or stays the same

**This is a major showstopper for our publishing process**, as our builds are usually very complex and highly dynamic (using autodoc with a special importer hook implementation) and last several hours, with a lots of assets (SVG created from [sphinx.ext.inheritance_diagram](https://www.sphinx-doc.org/en/master/usage/extensions/inheritance.html) ) to be published, which is unusually slow anyway.

The behavior can however be reproduced with a small and simple static RST documentation set as well.
I am relatively sure this did not happen with some older versions of sphinxcontrib-confluencebuilder.

### Environment / Configuration
Sphinx                          4.5.0
sphinx-epytext                  0.0.4
sphinx-rtd-theme                1.0.0
sphinxcontrib-applehelp         1.0.2
sphinxcontrib-confluencebuilder 1.8.0
sphinxcontrib-devhelp           1.0.2
sphinxcontrib-htmlhelp          2.0.0
sphinxcontrib-jsmath            1.0.1
sphinxcontrib-qthelp            1.0.3
sphinxcontrib-serializinghtml   1.1.5
sphinxcontrib-websupport        1.2.3

```
(system)
 platform: Windows-10-10.0.19041-SP0
   python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
   sphinx: 4.4.0
 requests: 2.26.0
  builder: 1.8.0

(configuration)
confluence_disable_autogen_title: True
confluence_global_labels: (set)
confluence_header_file: conf_header.tpl
confluence_ignore_titlefix_on_index: True
confluence_page_hierarchy: True
confluence_parent_page: (set)
confluence_prev_next_buttons_location: top
confluence_publish: True
confluence_publish_postfix:  9.9.9
confluence_server_pass: (set)
confluence_server_url: https://<removed>
confluence_server_user: (set)
confluence_space_key: (set; upper)
confluence_title_overrides: {'index': 'Development Manual 9.9.9'}

(confluence instance)
 connected: yes
   fetched: yes
   decoded: yes
    parsed: yes
      type: confluence
   version: 7.13.4
     build: 14866
```

**Comment by jdknight** [comment]
Checked some previous versions of this extension and tested with a couple of Confluence server versions, and it appears that creating labels for new pages never worked on Confluence server installations (only Confluence Cloud).

Adjustments have been made in #664 to address this. This change has been added into the main branch and should be made available next stable release. If users wish to use this capability before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

If this does not resolve your issue, please let me know.

**Comment by RobertSeeger** [comment]
Thanks a lot for the fast reaction and your support for the Confluence server version!
Looking forward to the next release then. :)

**Comment by RobertSeeger** [comment]
I can confirm that my use case is now resolved with the development version.
