### ISSUE TITLE
draw.io support

### ISSUE THREAD

**Issue by girivs82** [sphinx-contrib/confluencebuilder#672]
I read from the documentation that images (raster/vector) are supported, so I can use .png for raster and .svg for vector diagrams, but I also have requirements to use draw.io (using the embedded draw.io confluence extension). I realise there is a sphinxcontrib-drawio (https://pypi.org/project/sphinxcontrib-drawio) extension, but not sure how well this interoperates with confluence builder if I were to, for example, use a directive like this:

.. drawio-image:: example.drawio
   :export-scale: 150

**Comment by jdknight** [comment]
Here's an example of using drawio with Confluence builder. First, ensure both extension are properly registered in Sphinx:

```
extensions = [
    'sphinxcontrib.confluencebuilder',
    'sphinxcontrib.drawio',
]
```

To configure a default SVG output for Confluence, the following option can be added to a Sphinx configuration:

```
drawio_builder_export_format = {'confluence': 'svg'}
```

And utilize the drawio extension's directives. For example:

```
.. drawio-figure:: test.drawio
    :align: left

.. drawio-image:: test.drawio
    :format: png
    :align: center

.. drawio-figure:: test.drawio
    :format: svg
    :align: right
```

The first figure will default to the value configured in `drawio_builder_export_format`, where other figures will use the explicit format provided.

**Comment by jdknight** [comment]
It has been over a month since this question has been asked. Hopefully the examples worked. If future attempts to use the `sphinxcontrib.drawio` extension that work with the `html` builder but fail with `confluence`, feel free to create a new issue outlining the details. Marking this issued as closed.
