### ISSUE TITLE
Emoticon directive

### ISSUE THREAD

**Issue by pe1uca** [sphinx-contrib/confluencebuilder#685]
I'd like to include confluence emoticons but there's no directive.  
They have this format `<ac:emoticon ac:name="cross" />`  

Or is there a way for me to include the tag directly and by pass the need for a custom directive?  
(I think the `encode_storage_format` function prevents this)

**Comment by jdknight** [comment]
At this time, the only way to utilize Confluence's `emoticon` macro is to use a [raw role](https://docutils.sourceforge.io/docs/ref/rst/roles.html#raw). For example:

```
.. role:: raw-confluence(raw)
   :format: confluence_storage

:raw-confluence:`<ac:emoticon ac:name="cross" />`: This is not completed.
```

We can plan for next release to include a helper role to allow users define something such as `` :confluence_emoticon:`cross` `` to inject emoticons.

**Comment by jdknight** [comment]
Changes (#686) have been made to include support for a `confluence_emoticon` role. This change has been added into the main branch and should be made available next stable release. If users wish to use this capability before a release is made, the development version of this extension can be installed.

It is assumed this will close off this issue after next release; however, if there is something else related to emoticons that has been missed, please do not hesitate to bring it up.

**Comment by jdknight** [comment]
v1.9 is now available on PyPI -- marking as closed.
