### ISSUE TITLE
Support for Sphinx v5.1.0

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#692]
As of Sphinx v5.1.0, this extension may fail to load for a user's environment with the following error:

```
Running Sphinx v5.1.0

Exception occurred:
  File ".\sphinx\registry.py", line 169, in create_builder
    builder = self.builders[name](app, env=...)  # type: ignore[arg-type]
TypeError: __init__() got an unexpected keyword argument 'env'
````

Users who are blocked by this may workaround this by performing one the following solutions until a new release has been made to PyPI:

0. **(recommended)** Update to the most recent version v5.1.1 (or newer).

```
pip install -U sphinx
```

1. Install the most recent development version of this extension:
 
```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git
```

2. Downgrade Sphinx to v5.0.2 by using the following command:

```
pip install sphinx==5.0.2
```

See also:

- https://github.com/sphinx-doc/sphinx/pull/10702
- https://github.com/sphinx-contrib/confluencebuilder/pull/691

**Comment by ilCatania** [comment]
Thank you, I ran into this and pinning `sphinx<5.1.0` as a workaround fixed it for me

**Comment by jdknight** [comment]
Note that Sphinx v5.1.1 has been released, which should address the issues observed when loading the most recent stable version of this extension (v1.8).

I will leave this issue open for a small window of time for reference (if users are still transitioning between versions).

**Comment by jdknight** [comment]
With v1.9 is now available on PyPI, there should be no longer an issue for users who may opt explicitly for a v.5.1.0 release. Marking as closed.
