### ISSUE TITLE
Base REST API endpoint (/rest/api) not returning JSON; prevents uploads

### ISSUE THREAD

**Issue by IAXES** [sphinx-contrib/confluencebuilder#695]
Good day,

I wasn't sure if this belonged under <https://github.com/sphinx-contrib/confluencebuilder/issues/624>, so here goes.

My IT department recently made changes to our Confluence server so that the various REST API endpoints (e.g. `https://host/rest/api/space`, `https://host/api/content`) etc. work (i.e. some other in-house tools can publish to Confluence, interact with it, etc.). However, the sphinx confluence builder does some kind of pre-flight-check, where it notes that the base endpoint/URL, i.e. `https:/host/rest/api` is HTML formatted (and returning 404's), very similar to what was described in this ticket: <https://community.atlassian.com/t5/Confluence-questions/Unable-to-authenticate-with-the-Confluence-server-using/qaq-p/1845385>, re:

```sh
Error-
[<.......> docs]$ make confluence
Running Sphinx v4.2.0
loading pickled environment... done
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.
REQ: GET
RSP: 404
URL: https://<...>.atlassian.net/wiki/rest/api
API: space
DATA: <not-or-invalid-json>
```

[I'm looking at Confluence's official REST API documentation](https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/), and unless I'm mistaken, it doesn't appear that the base URL/endpoint is part of the API itself (i.e. no `GET`, `POST`, etc.; calls appear to be made to the `/` endpoint when interacting with it; this is just from a cursory analysis, I could be wrong here).

If this is the case, would be be reasonable to add some kind of flag for `conf.py` that equates to "skip sanity check of base endpoint/URL, we know the API is there"?

Thank you.

**Comment by jdknight** [comment]
Yup, this looks to be the same issue as the referenced one, which was addressed in #661. By utilizing the `confluence_publish_disable_api_prefix` configuration item in a v1.9 release, this extension will not include the "bind path". For example, if a configuration had the following before:

```python
confluence_server_url = 'https://host/'
```

It would be change to the following (based on the example URL mentioned above):

```python
confluence_server_url = 'https://host/api/'
confluence_publish_disable_api_prefix = True
```

Unfortunately, there has not been a stable release that has included this change. There is a plan to make a stable release this month (trying to close off two pull requests, if possible). For the interim, the only recommended way to handle such a scenario is to [use a development version of this extension](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation). For example:

```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git
```

If interested in a more "fixed" development snapshot, the following hash should work:

```
pip install git+https://github.com/sphinx-contrib/confluencebuilder.git@46f2e327121efe72ede387ebd447133aa030838b
```

**Comment by IAXES** [comment]
Thank you very much @jdknight 

As a follow-up: would it be reasonable/practical to manually apply #661 to a local checkout of the latest official release (i.e. 1.8) or should I strictly stick with the snapshot you noted above? Also, thanks for the help/one-liner to install it :)

Also, thanks to you + the team for this plugin. Saves me a ton of time not having to move `md`/`rST`/`txt`/etc. out of git and into a write-only doc system.

**Comment by jdknight** [comment]
For sure. If you just wanted to tweak the stable release's implementation on a system/container/etc., that should work. You could try to apply the patch from the commit, but a possibly simpler solution may be to adjust the value of [`API_REST_BIND_PATH`](https://github.com/sphinx-contrib/confluencebuilder/blob/v1.8/sphinxcontrib/confluencebuilder/std/confluence.py#L11) to an empty string. For example:

<sub>[sphinxcontrib/confluencebuilder/std/confluence.py]</sub>
```python
API_REST_BIND_PATH = ''
```

**Comment by IAXES** [comment]
I tried this setting/override in `/usr/lib/....../confluence.py`:

```py
API_REST_BIND_PATH = ''
```

However, that yields the following error:

```sh
  self.builder.init()                                                                                                                                                              [5/3025]

  File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/confluencebuilder/builder.py", line 128, in init
    self.warn('normalizing confluence url from '
  File "/usr/local/lib/python3.8/dist-packages/sphinxcontrib/confluencebuilder/logger.py", line 111, in warn
    ConfluenceLogger.logger.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1812, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/work/.local/lib/python3.8/site-packages/sphinx/util/logging.py", line 123, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1844, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1512, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 811, in filter
    result = f.filter(record)
  File "/work/.local/lib/python3.8/site-packages/sphinx/util/logging.py", line 426, in filter
    raise exc
sphinx.errors.SphinxWarning: normalizing confluence url from https://host.com/basepath/ to
Warning, treated as error:
```

Additionally, I tried the snapshot build you linked, but that yields a different error:

```sh
Running Sphinx v1.8.5

loading translations [en]... done

 

Extension error:

Could not import extension sphinxcontrib.bibtex (exception: cannot import name 'SphinxPostTransform' from 'sphinx.transforms.post_transforms' (/usr/lib/python3/dist-packages/sphinx/transfor

ms/post_transforms/__init__.py))

make[1]: *** [Makefile:53: html] Error 2
```

For the second use case, do I just need to install a new/beta version of Sphinx? (i.e. build from source so it's newer than the 1.8.0 that Ubuntu 20.04 seems to use by default)?

**Comment by IAXES** [comment]
It's working now! :) 

What I had to do was install Sphinx via pip, i.e. `python3 -m pip install sphinx`, rather than via apt, i.e. `sudo apt install python3-sphinx`. That, plus using your release branch at `46f2e327121efe72ede387ebd447133aa030838b`, got everything working.

Thanks again!
