### ISSUE TITLE
java.lang.ClassCastException when trying to set the "root" parameter

### ISSUE THREAD

**Issue by nwzy** [sphinx-contrib/confluencebuilder#700]
Hi all, I'm trying to add the page-tree macro on my confluence page. I usually have the setting `root = @self` for it, but it causes a `java.lang.ClassCastException`

I've tested it with `confluence_publish_root` set and unset (from #517)

Thank you!

## Report
```
(system)
 platform: Linux-4.15.0-156-generic-x86_64-with-glibc2.27
   python: 3.9.1 (default, Jul 1 2021, 10:08:58) [GCC 7.5.0]
   sphinx: 5.1.1
 requests: 2.25.1
  builder: 1.9.0.dev0

(configuration)
confluence_page_hierarchy: True
confluence_publish: True
confluence_publish_root: (set)
confluence_server_url: https://<removed>
confluence_server_user: (set)
confluence_space_key: (set; user)

(confluence instance)
 connected: no
```

## Error

The command below causes the error:

```
# Does not work
.. raw:: confluence_storage

   <ac:structured-macro ac:name="pagetree" ac:schema-version="1">
      <ac:parameter ac:name="root">@self</ac:parameter>
      <ac:parameter ac:name="sort">natural</ac:parameter>
   </ac:structured-macro>
```

But works if I remove the `root` line:

```
# This works
.. raw:: confluence_storage

   <ac:structured-macro ac:name="pagetree" ac:schema-version="1">
      <ac:parameter ac:name="sort">natural</ac:parameter>
   </ac:structured-macro>
```

Error output:
```
Running Sphinx v5.1.1
building [mo]: all of 0 po files
building [confluence]: all source files
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                                                                              
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                                                               
publishing documents... [ 33%] index                                                                                                                                                                                         
sphinxcontrib.confluencebuilder error:

---
Unsupported Confluence API call

An unsupported Confluence API call has been made. See the following
details for more information:

REQ: PUT
RSP: 500
URL: https://<removed>.com/rest/api
API: content
DATA: {
  "statusCode": 500,
  "data": {
    "authorized": false,
    "valid": true,
    "allowedInReadOnlyMode": true,
    "errors": [],
    "successful": false
  },
  "message": "java.lang.ClassCastException: java.lang.String cannot be cast to com.atlassian.confluence.xhtml.api.Link",
  "reason": "Internal Server Error"
}
```

**Comment by jdknight** [comment]
It appears the `root` parameter requires its content to a link to the desired content. If looking to target `@self`, the following appears to be Confluence's desired format:

```
<ac:structured-macro ac:name="pagetree" ac:schema-version="1">
    <ac:parameter ac:name="root"><ac:link><ri:page ri:content-title="@self" /></ac:link></ac:parameter>
    <ac:parameter ac:name="sort">natural</ac:parameter>
</ac:structured-macro>
```

**Comment by nwzy** [comment]
> It appears the `root` parameter requires its content to a link to the desired content. If looking to target `@self`, the following appears to be Confluence's desired format:
> 
> ```
> <ac:structured-macro ac:name="pagetree" ac:schema-version="1">
>     <ac:parameter ac:name="root"><ac:link><ri:page ri:content-title="@self" /></ac:link></ac:parameter>
>     <ac:parameter ac:name="sort">natural</ac:parameter>
> </ac:structured-macro>
> ```

This solved it! How did you figure out the syntax for working the macros? I can't seem to find the documentation for how to form the `structured-macro`

**Comment by nwzy** [comment]
For the curious, I searched until I found the [Confluence Storage Format](https://confluence.atlassian.com/doc/confluence-storage-format-790796544.html) documentation and under the header "Links" found an example of the call required

Although I'm still wondering how @jdknight found to pass this exact format of the parameter 

Thanks again, will close but am open to the thought process!

**Comment by jdknight** [comment]
I do not believe there is a complete storage format DTD provided by Confluence. I have stumbled upon some DTDs before, but nothing that ever seemed to be complete.

Typically, the best approach to replicating a macro type is to first use the macro type on a Confluence page and publish it. From the published page, you can select the options of the page to "View Storage Format" and replicate raw or custom macro directives from the sample content.
