### ISSUE TITLE
Confluence layouts

### ISSUE THREAD

**Issue by pe1uca** [sphinx-contrib/confluencebuilder#724]
I'm using a layout with several horizontal and vertical sections and AFAIK there's no support yet for this (along other tags).  

With the "View Storage Format" option from confluence I got the code to use with the raw role.   
But this always adds a top level `<p>`, which makes the rest of the format misbehave.  

Should the extra `<p>` tag be removed when trying use raw for the whole page?   
Or would better to add the directive to handle the layouts?  

---

Here's my page's code

```rst
.. role:: raw-confluence(raw)
      :format: confluence_storage

=============
Documentation
=============


:raw-confluence:`<raw storage format>`
```

Here's the example page I'm using.  
When running the builder is sent as is, except for the `<p>` tag wrapping it.  
```xml
<ac:layout>
	<ac:layout-section ac:type="single">
		<ac:layout-cell>
			<p>
				<br />
			</p>
		</ac:layout-cell>
	</ac:layout-section>
	<ac:layout-section ac:type="three_equal">
		<ac:layout-cell>
			<h2>Search this documentation</h2>
			<p>
			</p>
			<h2>Popular Topics</h2>
			<p>
			</p>
		</ac:layout-cell>
		<ac:layout-cell>
			<h2>Featured Pages</h2>
			<p>
			</p>
		</ac:layout-cell>
		<ac:layout-cell>
			<h2>Recently Updated Pages</h2>
			<p>
			</p>
		</ac:layout-cell>
	</ac:layout-section>
</ac:layout>
```

**Expected result:**  
![Screenshot 2022-09-22 133030](https://user-images.githubusercontent.com/15692727/191813750-51226414-3401-4857-8ddc-1597b657dc5f.png)

**Actual result:**   
![Screenshot 2022-09-22 132619](https://user-images.githubusercontent.com/15692727/191813709-dd82b977-1010-4e1b-82c5-f84cae0ebd50.png)

**Comment by jdknight** [comment]
For this use case, I believe you will want to use a [raw directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) over the use of a [raw text role](https://docutils.sourceforge.io/docs/ref/rst/roles.html#raw). When using the raw-role, it is not so much as that the raw directive is being wrapped in a paragraph, but that the document is defining a paragraph which contains a inlined raw role inside it.

Here is an example of a directive definition which may help you achieve what you want:

```
.. raw:: confluence_storage

    <ac:layout>
        <ac:layout-section ac:type="single">
            <ac:layout-cell>
                Content
            </ac:layout-cell>
        </ac:layout-section>
        <ac:layout-section ac:type="three_equal">
            <ac:layout-cell>
                <h2>Search this documentation</h2>
                <ac:structured-macro ac:name="livesearch" />
                <br />
                <h2>Popular Topics</h2>
                <ac:structured-macro ac:name="popular-labels" />
            </ac:layout-cell>
            <ac:layout-cell>
                <h2>Featured Pages</h2>
                <ac:structured-macro ac:name="contentbylabel">
                    <ac:parameter ac:name="cql">label = &quot;mytag&quot;</ac:parameter>
                </ac:structured-macro>
            </ac:layout-cell>
            <ac:layout-cell>
                <h2>Recently Updated Pages</h2>
                <ac:structured-macro ac:name="recently-updated">
                    <ac:parameter ac:name="hideHeading">true</ac:parameter>
                </ac:structured-macro>
            </ac:layout-cell>
        </ac:layout-section>
    </ac:layout>
```

The above content should not be wrapped with any paragraph tag.

**Comment by pe1uca** [comment]
Ah, got it. It works properly, thanks!
