### ISSUE TITLE
Missing padding for line block

### ISSUE THREAD

**Issue by pe1uca** [sphinx-contrib/confluencebuilder#725]
I was testing the new code for v2 about line block.  

I think it's missing the padding-top from the previous node.  
Maybe that part should be out of the else to apply to both versions?  
https://github.com/sphinx-contrib/confluencebuilder/blob/bd026c814a8a46a402e7ec9094d1d9ba519b252a/sphinxcontrib/confluencebuilder/storage/translator.py#L2529-L2548   

What I mean can be seen in this example where some of the line blocks are in different paragraphs but with v2 are rendered as in the same one.    
```rst
Our endpoints are described in this link  

| That documentation is mainly meant to generate libraries for different languages and tools (like postman) to easily call us.  
| For a more human comprehensive documentation of what each endpoint does, their parameters and responses you can continue reading.

.. note:: | **Old format**  
   |
	  Old format is officially  deprecated.
   | Some properties could've been different.  

   | For new ones the three first properties should be the same, so all tools can share the same identifier.
   | `label` can be different but is recommended to be the same.  
```

Excepted: 
![image](https://user-images.githubusercontent.com/15692727/192590550-12054cef-f82f-4ec1-80c9-23407ddf2602.png)

Actual:  
![image](https://user-images.githubusercontent.com/15692727/192590677-353639e4-e508-43cc-ac62-a4699bb3f48a.png)

**Comment by jdknight** [comment]
@pe1uca, thanks for taking the time to try it out and providing this report/example (it helps a lot).

A change has been applied via #726 which should address this issue. Please feel free to try it out and report any issues you may see.

**Comment by jdknight** [comment]
v2.0 is now available on PyPI -- marking as closed.
