### ISSUE TITLE
Does not parse ZWNJ character correctly

### ISSUE THREAD

**Issue by ParSal123** [sphinx-contrib/confluencebuilder#729]
Hi,
Version 1.9.0

The [ZWNJ character](https://en.wikipedia.org/wiki/Zero-width_non-joiner) is not shown in confluence:

In rst file and html output: `می‌شود`
in Confluence: `میشود`

**Comment by jdknight** [comment]
@ParSal123, thanks for the report. Merged in a change (#730) which should resolve this issue. If you would like to try it out now, you may install the [bleeding edge sources](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation). If you do, please let me know if there are any issues with the fix. The change should be available next release (v2.0+).

**Comment by ParSal123** [comment]
Thank you!
