### ISSUE TITLE
unknown node: JupyterCellNode

### ISSUE THREAD

**Issue by slavakx** [sphinx-contrib/confluencebuilder#733]
Hi, 

{jupyter-execute} from jupyter_sphinx doesn't work during upload. We get unknown node: JupyterCellNode 
Do you have a solution for this? This is the only problem we are facing with confluencebuilder. Everything else works fine. 

Thanks

**Comment by jdknight** [comment]
A change has been applied via #735 and merged into the development tree which should improve support for the use of nbsphinx and the Jupyter Sphinx extension. If interested in trying this capability before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed. Feedback is welcome.

**Comment by slavakx** [comment]
The development version works. Thanks for your quick fix.
