### ISSUE TITLE
Prevent publishing outside of confluence_publish_root

### ISSUE THREAD

**Issue by tucked** [sphinx-contrib/confluencebuilder#736]
Is there a way to prevent anything from being published outside of `confluence_publish_root`?
Today, this appears to happen for documents that aren't in any toctree.

**Comment by jdknight** [comment]
This is most likely a bug. From a quick inspection, it appears the default/fallback parent page for documents does not consider the case when `confluence_publish_root` is configured. This may be corrected with a change to this line:

https://github.com/sphinx-contrib/confluencebuilder/blob/703ee5444f84ef08f088f1af689543f7528e91be/sphinxcontrib/confluencebuilder/publisher.py#L244

To be something like:

```
base_page_id = self.config.confluence_publish_root
```

**Comment by jdknight** [comment]
Changes (#740) have been made to ensure orphan documents will respect the [`confluence_publish_root`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration/#confluence-publish-root) configuration. This change has been added into the main branch and should be made available next stable release. If users wish to use this capability before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

**Comment by jdknight** [comment]
v2.0 is now available on PyPI -- marking as closed.
