### ISSUE TITLE
Support embedding LucidCharts or iFrames in documents

### ISSUE THREAD

**Issue by prune998** [sphinx-contrib/confluencebuilder#757]
Hi,

While where's transitionning our docs "as-code", we haven't found a way to insert LucidCharts documents, or even insert `<iFrame>` HTML tags so the resulting Confluence page displays the thing correctly.

Is there a way to achieve this ? 

Thanks

**Comment by jdknight** [comment]
I do not believe this extension can do much for LucidCharts documents. There is no Sphinx extension that appears to provide LucidCharts capabilities to integrate with. Also, if LucidCharts did provide a way to host remote charting capabilities, there does not appear to be any available documentation online on how to achieve this.

As for iframes, it is possible to utilize the `iframe` macro in Confluence Cloud (I do not believe this macro is available on Confluence server/data center). There does not exist a directive at this time, but can be achieved by doing something such as following in reStructuredText:

```
.. raw:: confluence_storage

    <ac:structured-macro ac:name="iframe">
        <ac:parameter ac:name="src">
            <ri:url ri:value="https://sphinxcontrib-confluencebuilder.readthedocs.io/" />
        </ac:parameter>
        <ac:parameter ac:name="width">700px</ac:parameter>
        <ac:parameter ac:name="height">1000px</ac:parameter>
    </ac:structured-macro>
```

Or, in a Markdown document:

````
```{raw} confluence_storage
<ac:structured-macro ac:name="iframe">
    <ac:parameter ac:name="src">
        <ri:url ri:value="https://sphinxcontrib-confluencebuilder.readthedocs.io/" />
    </ac:parameter>
    <ac:parameter ac:name="width">700px</ac:parameter>
    <ac:parameter ac:name="height">1000px</ac:parameter>
</ac:structured-macro>
```
````

**Comment by prune998** [comment]
thanks @jdknight. I tried the `raw` syntax yesterday but it wasn't doing anything in the final docs. But I will test with your specific syntax.
Will report here.

**Comment by prune998** [comment]
MANY THANKS !

Using your code snippet and using the `embed` URL from Lucidchart worked !!

Just go to `file` -> `embed` then `Activate` the embed code and copy the URL over (URL only, you don't need the HTML around) :
````
```{raw} confluence_storage
<ac:structured-macro ac:name="iframe">
    <ac:parameter ac:name="src">
        <ri:url ri:value="https://lucid.app/documents/embedded/40000066-a000-000-0000-000000dc2e" />
    </ac:parameter>
    <ac:parameter ac:name="width">100%</ac:parameter>
    <ac:parameter ac:name="height">800px</ac:parameter>
</ac:structured-macro>
```
````
