### ISSUE TITLE
code-block JSON highlighting is not supported

### ISSUE THREAD

**Issue by karimtera** [sphinx-contrib/confluencebuilder#763]
Hello all,

Thanks for the awesome builder, I have a little trouble with JSON highlighting.

Issue:
```rst
.. code-block:: JSON

  {
    "REPO": "/x/y/z"
  }

```  

Result:
`WARNING: unsupported code language for confluence: json`

However, in the documentation it's mentioned that any language supported by the code macro in Confluence is supported.

P.S. I use Confluence editor v1, Sphinx v6.1.3

**Comment by jdknight** [comment]
@karimtera, unfortunately, `json` is not a valid format type for the [Confluence v1 editor](https://confluence.atlassian.com/doc/code-block-macro-139390.html). Atlassian only provides stock support for JSON with their v2 editor.

If you are using the v1 editor on an self-hosted instance that shows `json`, it could be that a system administrator may have added support for that language type. If that is the case, one approach is to use the [`confluence_lang_transform`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_lang_transform) option to help force custom language types.

**Comment by karimtera** [comment]
> If you are using the v1 editor on an self-hosted instance that shows `json`, it could be that a system administrator may have added support for that language type. If that is the case, one approach is to use the [`confluence_lang_transform`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_lang_transform) option to help force custom language types.

Yes, that's actually the case, thanks for your help!
