### ISSUE TITLE
Is there a way to updating the content?

### ISSUE THREAD

**Issue by slavakx** [sphinx-contrib/confluencebuilder#772]
Hi 
I might have missed a parameter in the documentation. Is there a method to remove the old content before uploading new content? For instance, if the project documentation has been updated with a different postfix via confluence_publish_postfix, uploading the new content would result in it being uploaded alongside the old content.
I tried confluence_cleanup_purge but it removed all entries under a confluence_parent_page
Thanks

**Comment by jdknight** [comment]
This extension does not attempt to track changes made to a Confluence space from a publish event. The [cleanup configuration option](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_cleanup_purge) works as follows:

- For the configured root page to publish into (if enabled), query for all child documents for that page.
- Publish page updates and new pages into Confluence.
- Any child documents not updated will be removed.

The goal of configuration options such as [prefix](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-publish-prefix)/[postfix](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-publish-postfix) options is to ensure a publish event will [not conflict with each other](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#confluence-spaces-and-unique-page-names) (i.e. to prevent a publish event from updates or delete pages from an independent prefix configuration).

If in a situation where there is a desire to delete various pages that fall outside of this extension's cleanup capability, the recommended options are to:
1. Manually delete desired pages using Confluence's UI; or,
2. One may attempt to use the [wipe utility command](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#wiping-a-space) provided by this extension (if there are a lot of pages to cleanup).
