### ISSUE TITLE
How to use support for sphinx_toolbox.collapse?

### ISSUE THREAD

**Issue by IceS2** [sphinx-contrib/confluencebuilder#792]
Hello folks!
I've been actually messing a lot with this extension but I'm really really new with Sphinx (Been trying to develop my own directives a little bit as well to learn more but I'm still pretty pretty green).

Checking the source code I saw the `transmute` files and how you support the `sphinx_toolbox.collapse` directive.

I tested it out but it doesn't render on Confluence. I'm getting the `WARNING: unknown node: CollapseNode`

How to use it?

Thanks a lot (=

**Comment by jdknight** [comment]
This is an issue with the Confluence builder extension as of Sphinx v6.1+. Newer versions of Sphinx will cache doctrees in a way where this extension's transmute logic will not function properly. A fix was applied in the development branch and will be available next release. See https://github.com/sphinx-contrib/confluencebuilder/issues/753 for workarounds for this issue (and possible other issues when using Sphinx v6.1+).

**Comment by IceS2** [comment]
Oh great! Thanks a lot for the info!
