### ISSUE TITLE
Support `Theme` attribute in `Code Block` macro (v1 editor)

### ISSUE THREAD

**Issue by bpandola** [sphinx-contrib/confluencebuilder#810]
Hi.  Thank you for the very useful package!

As the title suggests, I'm looking to have support for the `Theme` attribute in `Code Block` macros.  I see this as an optional setting in `conf.py` (e.g. `confluence_code_block_theme`) that would apply to all `Code Block` macros in the rst file(s).

I'm happy to have a go at implementing this myself, if it's something you would consider merging.  Thanks!

**Comment by jdknight** [comment]
Feature has been merged it and will be available next release (v2.2); thanks for the contribution.
