### ISSUE TITLE
Is there a way to set the parent page individually for each rst file rather than globally?

### ISSUE THREAD

**Issue by mikehas** [sphinx-contrib/confluencebuilder#822]

**Comment by jdknight** [comment]
> Is there a way to set the parent page individually for each rst file rather than globally?

Sorry, this is not a supported capability at this time.

**Comment by jdknight** [comment]
Adjustments have been applied via #825 and merged into the development tree which now introduces support for a `confluence_parent_override_transform` configuration option. This configuration will be considered an advanced publish option and may not work as expected with other options (e.g. purging). The new transform will allow users to add into their configuration a function definition to override the target identifier a page is published under. An example configuration is as follows:

```
def my_publish_override(docname, parent_id):
    if docname == 'special-doc':
        return 123456

    return parent_id

confluence_parent_override_transform = my_publish_override
```

This configuration will be available in the next release (v2.2+). For users wanting this capability before a release is made, the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension can be installed.

**Comment by jdknight** [comment]
v2.2 is now available on PyPI -- marking as closed.

**Comment by mikehas** [comment]
Awesome Thanks!
