### ISSUE TITLE
ca.crt 

### ISSUE THREAD

**Issue by danieltuzes** [sphinx-contrib/confluencebuilder#836]
When I set up `confluence_ca_cert = 'ca.crt'`, I get the error saying
OSError: could not find a suitable tls ca certificate bundle, invalid path: ca.crt

I am sure that the file is found by sphinx given the relative path, bc if I rename it to ca.bak, confluencebuilder  complains that `confluence_ca_cert is not a file`

However, if I set path as absolute, there is no problem.

**Comment by jdknight** [comment]
Looks to be an issue of how this extension forwards the configured CA path to Requests. When this extension performs a configuration check, the logic will accept either an absolute path or a relative path that is based in the project's source directory. After this check is done, it leaves the configuration as it and eventually gives the path reference to Requests. However, Requests is not informed (for relative paths) that the CA path sides inside the project's source directory. In this case, the `OSError` can occur.

This issue should be resolved with the fixes introduced in #839. Feel free to try these changes using a [development installation](https://sphinxcontrib-confluencebuilder.readthedocs.io/install/#development-installation). However, you may wait still next release or (as you have mentioned) use an absolute path instead.

Also, thanks for reporting this.

**Comment by jdknight** [comment]
v2.3 is now available on PyPI -- marking as closed.
