### ISSUE TITLE
Editor v2: Plantuml captions with emphasis generates invalid .conf file

### ISSUE THREAD

**Issue by Paldari** [sphinx-contrib/confluencebuilder#854]
Uml directive with emphasis text in the caption leads to invalid page generated for editor v2.
``</em>`` tag is not inserted at the correct place.

### Tested with:
```
(system)
 platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
   python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
   sphinx: 7.2.6
 docutils: 0.18.1
 requests: 2.31.0
  builder: 2.3.0

(configuration)
confluence_disable_notifications: True
confluence_editor: v2
confluence_full_width: True
confluence_page_hierarchy: True
confluence_parent_page: (set)
confluence_publish: True
confluence_server_url: https://<removed>
confluence_space_key: (set; upper)
confluence_timeout: 10

(confluence instance)
 connected: no
```
```
sphinxcontrib.plantuml 0.27
```

### Simple reproducer:
```
=============================
UML with caption and emphasis
=============================

.. uml::
    :caption: *simple* test
    :align: center

    @startuml
    actor Client
    participant Server
    Client -> Server
    @enduml

```

### Generates:
```
<p><ac:image ac:align="center" ac:alt="@startuml
actor Client
participant Server
Client -&gt; Server
@enduml">
<ri:attachment ri:filename="plantuml-c6673cc5b0adb11b77423984194011565ae365e7.png"></ri:attachment>
<ac:caption><em>simple test</ac:caption>
</ac:image></em><div style="clear: both"> </div>
<ac:image ac:alt="*simple* test">
<ri:attachment ri:filename="atlassian.png"></ri:attachment>
</ac:image>
```

I'll submit a really simple PR that fixes it, even though I don't really understand why this part of the code specific to v2 was needed ^^ (so the fix could be wrong).

**Comment by jdknight** [comment]
Thanks for reporting and setting up the PR. It all looks great. I was planning on maybe adding a crude unit test to sanity check this in the future, hence why I haven't immediately added it in (hope that doesn't block you).

For your comment on v2-specific, the fix is still good. For v2, images have a caption tag which we try to process there, so it is the only editor type which has this issue. The original/fallback caption logic would build it's own paragraph after an image for the caption text.

**Comment by Paldari** [comment]
Thank you for the clarifications.
And no problem, I'm not blocked for now :)

**Comment by jdknight** [comment]
v2.4 is now available on PyPI -- marking as closed.
