### ISSUE TITLE
Raw html file inclusion doesn't work

### ISSUE THREAD

**Issue by slavakx** [sphinx-contrib/confluencebuilder#869]
I am using the following block to include a raw hml file into the sphinx: 
It works fine locally but not with confluence builder. The confluence page is empty. 
Is there any workaround? 

`
```{eval-rst}
.. raw:: html
    :file: file.html
```
`

Thanks

**Comment by jdknight** [comment]
The [`raw` directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) is passing through content (as expected) when using the `html` builder, for raw content flagged for `html`.

If looking for the tag to use to pass in raw Confluence storage format content into a document, the build format should be identified with the `confluence_storage` tag:

```
.. raw:: confluence_storage

   ...
```

Although, if looking to pass in raw HTML into Confluence builder, there may be an interest in the unsupported [`confluence_permit_raw_html` option](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_permit_raw_html).

**Comment by jdknight** [comment]
It is believed that there are existing options to handle OP's use case (mentioned above). Therefore, I will be marking this issue as closed. Please feel free to re-open this issue or create a new one with more details if there is an issue with any of these options (that should be supported by this extension).
