### ISSUE TITLE
Exception in builder.py if self.legacy_pages is None

### ISSUE THREAD

**Issue by jameyhicks** [sphinx-contrib/confluencebuilder#880]
Sphinx version: 5.3.0
Python version: 3.11.6 (CPython)
Docutils version: 0.19
Jinja2 version: 3.1.2
Last messages:
  done
  publishing assets... [ 12%] AmbaUSB-1-opened.png
  publishing assets... [ 25%] AmbaUSB-2-cv25.png
  publishing assets... [ 37%] AmbaUSB-3-board-detected.png
  publishing assets... [ 50%] AmbaUSB-4-programming.png
  publishing assets... [ 62%] e106e85aa4094619d8b99d9f0cc467bbba1f5284f561430713a68623a3421976.svg
  publishing assets... [ 75%] 546d117c662f88bae4ac30f1a0179b18811ac195484e0a031eb5b1fad288e9ff.svg
  publishing assets... [ 87%] f71ce4a2c0d3440034ee594e6a91f38a0bc2998313c3ede9a9ddbc3fce291c03.svg
  publishing assets... [100%] objects.inv

Loaded extensions:
  sphinx.ext.mathjax (5.3.0) from /usr/local/lib/python3.11/site-packages/sphinx/ext/mathjax.py
  sphinxcontrib.applehelp (1.0.7) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/applehelp/__init__.py
  sphinxcontrib.devhelp (1.0.5) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/devhelp/__init__.py
  sphinxcontrib.htmlhelp (2.0.4) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/htmlhelp/__init__.py
  sphinxcontrib.serializinghtml (1.1.9) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/serializinghtml/__init__.py
  sphinxcontrib.qthelp (1.0.6) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/qthelp/__init__.py
  alabaster (0.7.13) from /usr/local/lib/python3.11/site-packages/alabaster/__init__.py
  recommonmark (0.7.1) from /usr/local/lib/python3.11/site-packages/recommonmark/__init__.py
  sphinxcontrib.httpdomain (unknown version) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/httpdomain.py
  sphinxcontrib.confluencebuilder (2.4.0) from /usr/local/lib/python3.11/site-packages/sphinxcontrib/confluencebuilder/__init__.py
  sphinxjsondomain (unknown version) from /Users/jamey/cmtelematics/iot-firmware/linuxfw/docs/source/sphinxjsondomain.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.11/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 379, in build
    self.finish()
  File "/usr/local/lib/python3.11/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 809, in finish
    if lpid is not None and lpid in self.legacy_pages:
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by jdknight** [comment]
Thanks for reporting this.

Changes (#881) have been made to correct this exception case. This change has been added into the main branch and should be made available next stable release. At this time, this issue does not affect instances using `confluence_cleanup_archive` or `confluence_cleanup_purge`. If blocked by this issue, it is recommended to either use the [development version](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/install/#development-installation) of this extension, or switch back to an older version of this extension.

**Comment by jameyhicks** [comment]
That is excellent news!

I am running the main branch now so I could implement a quick fix to the
problem. I am planning to use one of the cleanup options but did not test
them right away because the doc said they are unsupported.

**Comment by jdknight** [comment]
v2.5 is now available on PyPI -- marking as closed.
