### ISSUE TITLE
Configure PyPI with a GitHub Trusted publisher

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/confluencebuilder#882]
@tonybaloney, I was wondering if you could configure the sphinxcontrib-confluencebuilder project on PyPI to allow GitHub to be a trusted publisher. I have [recently been playing with Actions to support publishing to PyPI](https://github.com/jdknight/nfsn-ddns/blob/main/.github/workflows/publish-pypi.yml), and was thinking of moving the responsibility of building/publishing official releases for this extension into Actions as well.

If willing and have no concerns, I believe these would be the options to set:

- Project: sphinxcontrib-confluencebuilder
- Owner: sphinx-contrib
- Repository name: confluencebuilder
- Workflow name: publish-pypi.yml
- Environment name: release

**Comment by tonybaloney** [comment]
Great idea, done!
