### ISSUE TITLE
How to achieve confluence's scroll version in sphinx-confluencebuilder

### ISSUE THREAD

**Issue by rakeshcbpur** [sphinx-contrib/confluencebuilder#964]
Hi Team,
Apologies, if this is the bug/issues forum , I am still asking this question.

We use below command to publish all the pages in current directory to configured confluence instance (conf.py)
python -m sphinx -b confluence . _build/confluence -E -a -Dconfluence_publish_token="TOKEN"

But in our case, the confluence instance is configured with different scroll versions like "WRITING", "2024", "2023" etc..

I am not sure if we can build/publish the pages to specific confluence scroll version say in our case "WRITING" using the above command or any other way ?

**Comment by jdknight** [comment]
@rakeshcbpur, I do not believe this extension can work with [Scroll Versions](https://marketplace.atlassian.com/apps/1210818/). From what I can tell, it has [its own API](https://help.k15t.com/scroll-versions/4.6/rest-api-resources) to manage resources which cannot be gracefully mapped to what this extension performs.
