### ISSUE TITLE
confluence-server-url

### ISSUE THREAD

**Issue by avkulkarni1620** [sphinx-contrib/confluencebuilder#968]
I want to migrate confluence to my personal url, how can we do that. What configuration I need to do ?
Do I need to change only confluence _server_url ?
Request to guide in this.

**Comment by jdknight** [comment]
The two key configurations would be [`confluence_server_url`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_url) and [`confluence_space_key`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_space_key). The values will depend on if the content is being posted to a personal Wiki of a Confluence Cloud instance or Confluence Data Center. If hosted on the same Confluence instance in your original configuration, you only need to update `confluence_space_key`. For `confluence_space_key`, set is to the name of the personal Wiki. This may be a value such as `~123456789` on Cloud, or may include the target username `~myusername` on other variants.

**Comment by avkulkarni1620** [comment]
We already migrated to data center, I am facing authentication error.

**Comment by jdknight** [comment]
- For authentication, are you using a [PAT](https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html) which you configure into a [`confluence_publish_token`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_publish_token) option? Also ensure `confluence_server_user` is not set.
- When configuring [`confluence_space_key`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confluence-server-pass) for a personal Wiki, ensure it includes the `~` prefix.
- If you have connection issues, maybe try the [troubleshooting mode](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#connection-troubleshooting)?

**Comment by avkulkarni1620** [comment]
Ok sure I will work on this

**Comment by avkulkarni1620** [comment]
![Uploading 20240603_120422.jpg…]()

still it is showing me error.

**Comment by jdknight** [comment]
@avkulkarni1620, the provided image did not appear to work. Can you re-attach and/or provide some output when trying to troubleshoot?

**Comment by jdknight** [comment]
This has been open for a couple a releases and more so looks to be a support case. If the issued case repeats itself with a recent release, feel free to re-open or create a new issue. For now, marking as closed.
