### ISSUE TITLE
Debugging "unknown node:"

### ISSUE THREAD

**Issue by neongreen-sc** [sphinx-contrib/confluencebuilder#969]
During a build, I encounter this warning:

```
WARNING: unknown node: PassthroughTextElement
```

However, it doesn't say which page causes it.

How can I debug this? I tried passing `-vvv` to sphinx-build but it didn't help.

**Comment by neongreen-sc** [comment]
Update: after searching the entire GitHub for `PassthroughTextElement`, it turns out that it comes from sphinx-design. Makes sense.

Still, is there any option to report document path / debug info / anything when an unknown node is encountered?

**Comment by jdknight** [comment]
At this time, there is no detailed output on [unknown node](https://github.com/sphinx-contrib/confluencebuilder/blob/v2.5.2/sphinxcontrib/confluencebuilder/translator.py#L168) scenarios in this extension. It does look like docutils does [track some data](https://sourceforge.net/p/docutils/code/HEAD/tree/tags/docutils-0.21/docutils/nodes.py#l46) that could be used to better detail the origin of unknown nodes.

**Comment by jdknight** [comment]
Changes have been introduced via #980, which should now attempt to print the origin document and line number when an unknown node is detected.

**Comment by jdknight** [comment]
v2.6 is now available on PyPI -- marking as closed.
