### ISSUE TITLE
Unable to authenticate to Confluence

### ISSUE THREAD

**Issue by Shaansarkar** [sphinx-contrib/confluencebuilder#971]
Hi Team,

I am facing an issue, below is the problem statement & possible approach which i tried.

We are currently migrating from one ASCENT WIKI to another Confluence Data center. We are able to create pages in the old ASCENT Wiki page using the config available but when we are trying to use the same config with the updated URL & SPACE key for new Confluence data center we are facing an **authentication issue**. 
- It is giving error as "**Unable to authenticate with Confluence**" . 

What we have done:
Passed username and Password
Created PAT token and had passed in confluence config argument
Created API token and passed
We are admins in space and are really unable to take a step forward and are stuck for long.
Sharing the snippet of the config for reference.

I tried to use REST APIs and was able to successfully create page just by passing the PAT which i tried to give input in the config.
REST APIs approach works but while using it through confluence builder i have facing error.

Can you help me in this as it has become a show stopper for me now?
Thanks.
<img width="430" alt="Config" src="https://github.com/sphinx-contrib/confluencebuilder/assets/170648295/4ba732e5-553e-43d6-ac50-56c71a4aa7f2">

**Comment by jdknight** [comment]
Any updates?

**Comment by Shaansarkar** [comment]
Hi James,

Sorry for the delayed reply. I was able to build the code and push data on the confluence using the PAT.
There was some tool version issue i guess at my end and also as you guided had helped me to resolve the issue.

Thanks a lot for your prompt help and solution.
