### ISSUE TITLE
Support rendering Mermaid with raw HTML blocks

### ISSUE THREAD

**Issue by neongreen-sc** [sphinx-contrib/confluencebuilder#972]
I work in an environment where `mermaid-cli` is tricky to install.

However, our Confluence Server instance has HTML enabled, and for Mermaid blocks we can simply output smth like:

```html
<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
</script>
<pre class="mermaid">
  .. diagram goes here ..
</pre>
```

This would be great to support natively.

**Comment by jdknight** [comment]
Does the [`confluence_permit_raw_html`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_permit_raw_html) option work for this use case?

**Comment by neongreen-sc** [comment]
Without `confluence_permit_raw_html`: confluencebuilder's mermaid override kicks in and says that it can't run `mmdc`.

With `confluence_permit_raw_html` and `confluence_adv_restricted = ["ext-sphinxcontrib.mermaid"]`: mermaid nodes aren't touched at all and we end up with "unknown node type: mermaid".

I haven't tried with `confluence_permit_raw_html` but without `confluence_adv_restricted` -- is it supposed to work? I would guess not.

**Comment by jdknight** [comment]
Sorry, I was under the assumption that you may have already hooked into sphinxcontrib-mermaid's implementation to have the HTML content generated for you. If you did something like this:

```
from sphinxcontrib.mermaid import html_visit_mermaid
from sphinxcontrib.mermaid import mermaid
...
def setup(app: Sphinx):
    app.add_node(mermaid, confluence=(html_visit_mermaid, None))
```

This could inject HTML into the body document that may work with `confluence_adv_restricted` enabled.

**Comment by jdknight** [comment]
Changes from #1037 should help support this through a new [`confluence_mermaid_html_macro` option](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration/#confval-confluence_mermaid_html_macro).

**Comment by jdknight** [comment]
v2.7 is now available on PyPI -- marking as closed.
