### ISSUE TITLE
Best practices for page title changes?

### ISSUE THREAD

**Issue by neongreen-sc** [sphinx-contrib/confluencebuilder#973]
Right now, when page title changes, confluencebuilder removes the old page entirely & creates a new page -- even if the content hasn't changed.

It seems like Confluence Server doesn't handle this situation well -- links to the old page start saying "This page has been deleted". Usually for a broken link Confluence says "maybe you meant X", but not in this case.

Are there any best practices for mitigating this? The following ideas come to mind:

* An extension that will modify `.rst` files to include published page IDs after publication?
* Keeping a local cache with path -> ID mappings? 
* ...smth else?

**Comment by neongreen-sc** [comment]
* Purging Confluence's "deleted pages" stash via API so that it never suggests a "deleted" page and is instead forced to guess based on the title?

**Comment by jdknight** [comment]
There is no graceful solution at this time. Only the parent page option (if used) accepts an explicit identifier, and there is non-trivial way exposed to users to override page identifiers for other pages. 

We could try to expose a hook for users to override the target identifier for a page. Would require some effort to ensure actions like dry-runs operate/report expected values with overrides -- assume if such an override could help. On this note (and related to the first suggestion made), we could try to add a page-id hint in [`confluence_metadata`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/directives/#directive-confluence_metadata). Not sure about having this extension edit user's documentation -- maybe provide a output for users of published pages and which page IDs were used.

Hesitant on supporting caching for tracking identifiers. If this extension did any caching, it would be typically be stored locally in an output directory and not something that may live between different environments (e.g. container builds) or runs (if users force to clear cache).

The closest thing may be the use of [`confluence_title_overrides`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_title_overrides) -- but this is an old option that was mainly designed for overriding specific documents with fixed names to a different name compatible with Confluence.

One approach that could be done is maybe this extension can provide a transform allowing a user to manipulate the entire title value based on the file document name and determined title value. Then users would be free to do any custom mappings they desire (e.g. use the file's document name as a title and set `confluence_remove_title = False`).

**Comment by jdknight** [comment]
There has not been activity on this thread for some time. Performing cleanup from this recent release, this thread will be marked as closed.

At the time of writing, there is not much this extension can do to automatically handle scenarios with page title changes and attempts to use the same page identifiers made from a previous release. A main factor for this, as mentioned above, is properly trying to handle caching of identifiers through some mapping of document files. This is not a capability that is desired to be handled by this extension (at least, this time).

With the v2.8 release, there has been some new capabilities added to give users more control on where pages are published. New [events](https://sphinxcontrib-confluencebuilder.readthedocs.io/events/) have been added to allow:
- Adding a hook which trigger when pages are published, supporting the ability to track page identifiers for certain documents.
- Adding a hook which allows a configuration for force/override a page identifier to use for an upload.

These two events should give advanced users the flexibility to control where documents are published outside the default methods of publishing with this extension.
