### ISSUE TITLE
Facing issue with Sphinx while connecting with SSO configured Confluence

### ISSUE THREAD

**Issue by tapas-baranwal** [sphinx-contrib/confluencebuilder#983]
Hi Team,

I hope your day is going well.

We are facing issue with Sphinx confluence Builder.
We are unable to establish connection between Confluence and Sphinx.
We are using SSO in our Confluence for Login.
Can you please help me how we can connect so that we use the Sphinx Confluence Builder?

Please see the attachment for error.
![image (11)](https://github.com/sphinx-contrib/confluencebuilder/assets/68471131/f077a891-d879-4a1d-8cbe-90e5c7f1b2a1)

**Comment by jdknight** [comment]
- Since it appears you are using a Confluence Cloud instance, are you using an [API token](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/) for your authentication (and not a password)? I'm not sure off hand if Cloud accepts user's account passwords anymore.
- Maybe try the [connection troubleshooting tool](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#connection-troubleshooting)?
- Is still experiencing issues, mind [generating a report](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/tips/#asking-for-help)?

**Comment by tapas-baranwal** [comment]
Hi James,

We try to use API tokens also. But it still not working. Due to Single Sign On we can't use Username and Password.

**Comment by jdknight** [comment]
Support for SSO-configured environments do not always have a straightforward solution. It depends on the SSO provided user (third-party or custom-made) and other special conditions that may have been enforced by system administrators of the Confluence instance. On top of that, there are no environments like these available to extension maintainers to test/verify on.

That being said, typically users deal with SSO scenarios by using the [`confluence_server_cookies`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_cookies) configuration key. This is for environments that use a browser to perform an authentication, which results in the generation of a cookie string value which in turn can be used in this extension's cookie injection option. A crude test would be to authenticate with a browser session, use the a browser development panel (e.g. F12) to retrieve a session token and trying it out with this extension. The process of acquiring a cookie value "properly" will vary per SSO solution. There was a discussion on an approach for an AWS SSO solution in https://github.com/sphinx-contrib/confluencebuilder/issues/728, but I cannot say it is a trivial process.

The only other immediate hints I can provide are if your environment provides client support for SSO authentication with a Python Requests module, you should be able to use the [`confluence_server_auth`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_auth) option to attach/use the implementation as the authentication module for this extension. Another approach may be to use [`confluence_publish_headers`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_publish_headers) to directly inject specific headers desired for your SSO instance, but the option still needs to be populated by whatever conditions/values expected for the SSO solution.

Finally, the use of [`confluence_publish_debug`](headers) could be helpful in debugging requests when using the value of `headers`. Some instances have a reverse proxy that can provide URL hints or error messages that may not be explicitly handled by this extension.

**Comment by tapas-baranwal** [comment]
(debug) Request]
GET https://energyaustralia.atlassian.net/wiki/rest/api/space/FPM
User-Agent: Sphinx Confluence Builder
Accept-Encoding: gzip, deflate
Accept: application/json; charset=utf-8
Connection: keep-alive
X-Atlassian-Token: no-check
Authorization: Basic c2ViYXN0aWFuLnB1c2NoZWxsb3ZlbmdyZWVuQGVuZXJneWF1c3RyYWxpYS5jb20uYXU6cGxTITMzcGxzNzNwbFMh

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): energyaustralia.atlassian.net:443
DEBUG:urllib3.connectionpool:https://energyaustralia.atlassian.net:443 "GET /wiki/rest/api/space/FPM HTTP/1.1" 403 None
(debug) Response]
Code: 403
Date: Tue, 25 Jun 2024 07:02:59 GMT
Content-Type: application/json
Server: AtlassianEdge
Atl-Confluence-Via: h:confluence-prod-ap-9-2.prod.atl-paas.net
Vary: Accept-Encoding
Cache-Control: no-cache, no-store, must-revalidate
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Warning: 299 - "Deprecated API, will be removed on Mon, 2 Dec 2024 00:00:00 GMT"
Deprecation: Wed, 1 Mar 2023 00:00:00 GMT
Link: <https://developer.atlassian.com/cloud/confluence/changelog/#CHANGE-864>; rel="deprecation"
Content-Encoding: gzip
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Atl-Traceid: 1d640c7ef7d942d6a1241b3a55d12858
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
Report-To: {"endpoints": [{"url": "https://dz8aopenkvv6s.cloudfront.net"}], "group": "endpoint-1", "include_subdomains": true, "max_age": 600}
Nel: {"failure_fraction": 0.001, "include_subdomains": true, "max_age": 600, "report_to": "endpoint-1"}
Transfer-Encoding: chunked


sphinxcontrib.confluencebuilder error:

---
Permission denied on Confluence (rest-call)

We are getting this. Can you please help me?

**Comment by jdknight** [comment]
@tapas-baranwal, it does not appear to me that you are using an [API token](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/) for what looks to be a Confluence Cloud instance. The value for [`confluence_server_pass`](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/stable/configuration/#confval-confluence_server_pass) should be set to a value looking like the following (example token below):

```
YDYDD3qVvKV0FbkErSxaQ2olmyUO8PP-hsREnXaP9sobDyAn7JuE_LtgBlL3mYX5kWvqXKAr3uK1RrLMmM5XYiAfZBVSmSIKwCIY26JbwxTMV8Igydrk7VzdS9sAyqMhq_Ct5S0PfmAiS_thhJb6NQNEOu56YLeVBAA-CuxQeapiTz_AMGwaPe8=02381T9A
```

I would also advise you change your password. Note that it is not recommended to share the contents of the `Authorization` header, as it will reveal credential details.

**Comment by jlumpe** [comment]
My organization uses SSO and I was just able to get it working with the `tenant.session.token` copied from my browser:

```python
confluence_server_cookies = {
    'tenant.session.token': 'XXXXX',
}
```

**Comment by jdknight** [comment]
There has not been activity on this thread for some time. Performing cleanup from this recent release, this thread will be marked as closed.

From this discussion, a [new guide](https://sphinxcontrib-confluencebuilder.readthedocs.io/guide-sso/) has been added into the documentation as an initial overview page on dealing with SSO and OAuth environments. Not that such a page will solve everyone's issue when setting up the first time, but it might provide some hints for a user to work out issues in their environments.
