### ISSUE TITLE
Mention sphinxnotes-strike in documentation

### ISSUE THREAD

**Issue by mkonig** [sphinx-contrib/confluencebuilder#997]
Hi

After experimenting a lot with your suggestions in the documentation about how to use strikethrough I was close to give up because nothing seemed to work.
Then I came across this sphinx extension: https://sphinx.silverrainz.me/strike/

Using this let me have strikethrough in html and confluence output.

Maybe you can mention this in your documentation.

**Comment by jdknight** [comment]
Updated the documentation (https://github.com/sphinx-contrib/confluencebuilder/pull/1000) to have a dedicated strike-related section. Feel free to [inspect the draft content](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/guide-strike/) and leave any comments.

**Comment by jdknight** [comment]
With the v2.6 release, the stable document should provide additional information on the strike-related capabilities -- marking as closed.
